using System;
using System.Linq;
using NUnit.Framework;
using Tsvrc.Editor;

namespace Tsvrc.Tests.Editor
{
    public class UdonWriterTests
    {
        private static string[] SplitLines(string text)
        {
            string[] parts = text.Split(new[] { Environment.NewLine }, StringSplitOptions.None);
            // ToString() always ends with a trailing newline from the last AppendLine;
            // drop the resulting empty final element so callers compare content lines only.
            if (parts.Length > 0 && parts[parts.Length - 1] == string.Empty)
                return parts.Take(parts.Length - 1).ToArray();
            return parts;
        }

        [Test]
        public void AutoGenHeader_WritesThreeCommentLines()
        {
            var writer = new UdonWriter();

            writer.AutoGenHeader();

            Assert.AreEqual(new[]
            {
                "// <auto-generated/>",
                "// Generated by TsGenerator. Do not edit, changes will be overwritten.",
                "// Regenerated automatically on domain reload, or manually via Tsvrc > Force Regenerate.",
            }, SplitLines(writer.ToString()));
        }

        [Test]
        public void Usings_WithNamespaces_WritesUsingLinesThenBlankLine()
        {
            var writer = new UdonWriter();

            writer.Usings(new[] { "System", "UnityEngine" });

            Assert.AreEqual(new[] { "using System;", "using UnityEngine;", "" }, SplitLines(writer.ToString()));
        }

        [Test]
        public void Usings_WithEmptyEnumerable_WritesOnlyBlankLine()
        {
            var writer = new UdonWriter();

            writer.Usings(Array.Empty<string>());

            Assert.AreEqual(new[] { "" }, SplitLines(writer.ToString()));
        }

        [Test]
        public void Namespace_WrapsBodyInBracesAndIndentsIt()
        {
            var writer = new UdonWriter();

            using (writer.Namespace("Foo.Bar"))
            {
                writer.Line("public class C {}");
            }

            Assert.AreEqual(new[]
            {
                "namespace Foo.Bar",
                "{",
                "    public class C {}",
                "}",
            }, SplitLines(writer.ToString()));
        }

        [Test]
        public void Class_WithAttribute_WritesAttributeLineBeforeClassHeader()
        {
            var writer = new UdonWriter();

            using (writer.Class("public", "Foo", "MonoBehaviour", "[Serializable]"))
            {
                writer.Line("int x;");
            }

            Assert.AreEqual(new[]
            {
                "[Serializable]",
                "public class Foo : MonoBehaviour",
                "{",
                "    int x;",
                "}",
            }, SplitLines(writer.ToString()));
        }

        [Test]
        public void Class_WithoutAttribute_OmitsAttributeLine()
        {
            var writer = new UdonWriter();

            using (writer.Class("public", "Foo", "MonoBehaviour"))
            {
            }

            Assert.AreEqual(new[]
            {
                "public class Foo : MonoBehaviour",
                "{",
                "}",
            }, SplitLines(writer.ToString()));
        }

        [Test]
        public void Block_WithNullHeader_WritesOnlyBraces()
        {
            var writer = new UdonWriter();

            using (writer.Block(null))
            {
                writer.Line("x");
            }

            Assert.AreEqual(new[] { "{", "    x", "}" }, SplitLines(writer.ToString()));
        }

        [Test]
        public void Block_WithEmptyHeader_WritesOnlyBraces()
        {
            var writer = new UdonWriter();

            using (writer.Block(""))
            {
            }

            Assert.AreEqual(new[] { "{", "}" }, SplitLines(writer.ToString()));
        }

        [Test]
        public void Block_Nested_IndentsEachDepthLevel()
        {
            var writer = new UdonWriter();

            using (writer.Block("outer"))
            {
                using (writer.Block("inner"))
                {
                    writer.Line("deep");
                }
            }

            Assert.AreEqual(new[]
            {
                "outer",
                "{",
                "    inner",
                "    {",
                "        deep",
                "    }",
                "}",
            }, SplitLines(writer.ToString()));
        }

        [Test]
        public void Method_BehavesLikeBlockUsingSignatureAsHeader()
        {
            var writer = new UdonWriter();

            using (writer.Method("public void Foo()"))
            {
                writer.Line("return;");
            }

            Assert.AreEqual(new[]
            {
                "public void Foo()",
                "{",
                "    return;",
                "}",
            }, SplitLines(writer.ToString()));
        }

        [Test]
        public void BlockScope_DisposedTwice_WritesClosingBraceOnlyOnce()
        {
            var writer = new UdonWriter();
            IDisposable scope = writer.Block("x");

            scope.Dispose();
            scope.Dispose();

            Assert.AreEqual(new[] { "x", "{", "}" }, SplitLines(writer.ToString()));
        }

        [Test]
        public void BlankLine_WritesEmptyLineBetweenContent()
        {
            var writer = new UdonWriter();

            writer.Line("a");
            writer.BlankLine();
            writer.Line("b");

            Assert.AreEqual(new[] { "a", "", "b" }, SplitLines(writer.ToString()));
        }

        [Test]
        public void Summary_WritesXmlDocCommentLine()
        {
            var writer = new UdonWriter();

            writer.Summary("Does a thing.");

            Assert.AreEqual(new[] { "/// <summary>Does a thing.</summary>" }, SplitLines(writer.ToString()));
        }

        [Test]
        public void Region_AndEndRegion_WritePragmaLines()
        {
            var writer = new UdonWriter();

            writer.Region("Fields");
            writer.Line("int x;");
            writer.EndRegion();

            Assert.AreEqual(new[] { "#region Fields", "int x;", "#endregion" }, SplitLines(writer.ToString()));
        }

        [Test]
        public void EndRegion_WithoutMatchingRegion_DoesNotThrow()
        {
            var writer = new UdonWriter();

            Assert.DoesNotThrow(() => writer.EndRegion());
            Assert.AreEqual(new[] { "#endregion" }, SplitLines(writer.ToString()));
        }

        [Test]
        public void Region_InsideBlock_IsIndentedWithTheBlock()
        {
            var writer = new UdonWriter();

            using (writer.Block("class C"))
            {
                writer.Region("Fields");
                writer.EndRegion();
            }

            Assert.AreEqual(new[]
            {
                "class C",
                "{",
                "    #region Fields",
                "    #endregion",
                "}",
            }, SplitLines(writer.ToString()));
        }
    }
}
