using System;
using NUnit.Framework;
using Tsvrc.Editor;

namespace Tsvrc.Tests.EditMode
{
    // Tests feed ConstructModule.GenerateCode() synthetic entries via reflection.
    public class ConstructModuleGenerateCodeTests
    {
        private static readonly Type EntryType = CodeGenModuleReflection.NestedType(typeof(ConstructModule), "ConstructEntry");

        private static ConstructModule BuildModule(params object[] entries)
        {
            var module = new ConstructModule();
            PrivateFieldAccess.SetField(module, "_entries", CodeGenModuleReflection.BuildList(EntryType, entries));
            return module;
        }

        private static object Entry(string name, string typeName, string ns)
            => CodeGenModuleReflection.BuildEntry(EntryType,
                ("Name", name), ("TypeName", typeName), ("Namespace", ns), ("SourceObject", null));

        [Test]
        public void GenerateCode_EmptyEntries_ReturnsStubWithEmptyStartMethod()
        {
            string expected =
$@"// <auto-generated/>
// Generated by TsGenerator. Do not edit, changes will be overwritten.
// Regenerated automatically on domain reload, or manually via Tsvrc > Force Regenerate.

namespace {ScaffoldModule.CompiledNamespace}
{{
    public partial class {ScaffoldModule.CompiledClassName}
    {{
        public void _TsConstructStart()
        {{
        }}
    }}
}}
";

            GeneratedCodeAssert.AreEqual(expected, BuildModule().GenerateCode());
        }

        [Test]
        public void GenerateCode_SingleEntry_UsesConstructPrefixedFieldNameAndAlwaysCallsTsConstruct()
        {
            // Every Constructs entry must be a TsBehaviour by config type, so unlike
            // Singleton/Pool there is no non-TsBehaviour branch to test here.
            var module = BuildModule(Entry("HudManager", "StateManager", "Tsvrc.StateMachine"));

            string code = module.GenerateCode();

            StringAssert.Contains("private StateManager _constructHudManager;", code);
            StringAssert.Contains("_constructHudManager.TsConstruct(this);", code);
        }

        [Test]
        public void GenerateCode_MultipleEntries_AreAlphabeticalByNameNotConfigOrder()
        {
            var module = BuildModule(
                Entry("Zebra", "StateManager", "Tsvrc.StateMachine"),
                Entry("Alpha", "StateManager", "Tsvrc.StateMachine"));

            string code = module.GenerateCode();

            int alpha = code.IndexOf("_constructAlpha", StringComparison.Ordinal);
            int zebra = code.IndexOf("_constructZebra", StringComparison.Ordinal);
            Assert.Greater(zebra, alpha);
        }

        [Test]
        public void GenerateCode_MultipleNamespaces_AreDedupedAndIncluded()
        {
            var module = BuildModule(
                Entry("A", "StateManager", "Tsvrc.StateMachine"),
                Entry("B", "StateManager", "Tsvrc.StateMachine"),
                Entry("C", "TsMemory", "Tsvrc.Utils"));

            string code = module.GenerateCode();

            int first = code.IndexOf("using Tsvrc.StateMachine;", StringComparison.Ordinal);
            int last = code.LastIndexOf("using Tsvrc.StateMachine;", StringComparison.Ordinal);
            Assert.AreEqual(first, last, "Duplicate namespace must appear only once.");
            StringAssert.Contains("using Tsvrc.Utils;", code);
        }
    }
}
