using NUnit.Framework;
using Tsvrc.Editor;

namespace Tsvrc.Tests.EditMode
{
    // Unlike every other module, InstanceModule.GenerateCode() does not vary with the
    // resolved _detectedType/_ambiguous state at all - it always emits the same fixed
    // field/property/method shape (the *scene wiring* is what varies, not the generated
    // source). This is easy to wrongly assume depends on config like the rest.
    public class InstanceModuleGenerateCodeTests
    {
        private static string Expected =>
$@"// <auto-generated/>
// Generated by TsGenerator. Do not edit, changes will be overwritten.
// Regenerated automatically on domain reload, or manually via Tsvrc > Force Regenerate.

using Tsvrc.Core;
using Tsvrc.Utils;
using UdonSharp;
using UnityEngine;

namespace {ScaffoldModule.CompiledNamespace}
{{
    public partial class {ScaffoldModule.CompiledClassName}
    {{
        [ReadOnly] [SerializeField] private TsInstance _instance;

        public override TsInstance Instance => _instance;

        public void _TsInstanceStart()
        {{
            _instance.TsConstruct(this);
            _instance.OnInstanceStart();
        }}
    }}
}}
";

        [Test]
        public void GenerateCode_WithNoDetectedType_MatchesFixedTemplate()
        {
            GeneratedCodeAssert.AreEqual(Expected, new InstanceModule().GenerateCode());
        }

        [Test]
        public void GenerateCode_WithDetectedTypeSet_IsIdenticalToNoDetectedType()
        {
            var module = new InstanceModule();
            PrivateFieldAccess.SetField(module, "_detectedType", typeof(TsInstanceStandIn));
            PrivateFieldAccess.SetField(module, "_ambiguous", false);

            GeneratedCodeAssert.AreEqual(Expected, module.GenerateCode());
        }

        // Only used as a non-null Type value for the reflection test above - never
        // constructed or added to a scene.
        private class TsInstanceStandIn
        {
        }
    }
}
