using NUnit.Framework;
using Tsvrc.Editor;

namespace Tsvrc.Tests.EditMode
{
    // LogModule.GenerateCode() has no config-driven variation at all (LoadConfig() is
    // a no-op). Mirrors MemoryModuleGenerateCodeTests.
    public class LogModuleGenerateCodeTests
    {
        [Test]
        public void GenerateCode_IsAFixedTemplate()
        {
            string expected =
$@"// <auto-generated/>
// Generated by TsGenerator. Do not edit, changes will be overwritten.
// Regenerated automatically on domain reload, or manually via Tsvrc > Force Regenerate.

using Tsvrc.Utils;
using UdonSharp;
using UnityEngine;

namespace {ScaffoldModule.CompiledNamespace}
{{
    public partial class {ScaffoldModule.CompiledClassName}
    {{
        [ReadOnly] [SerializeField] private TsLogger _log;

        public override TsLogger Log => _log;

        public void _TsLogStart()
        {{
            _log.TsConstruct(this);
        }}
    }}
}}
";

            GeneratedCodeAssert.AreEqual(expected, new LogModule().GenerateCode());
        }
    }
}
