using System;
using System.Collections;
using System.Collections.Generic;
using NUnit.Framework;
using Tsvrc.Editor;

namespace Tsvrc.Tests.EditMode
{
    // Tests feed PoolModule.GenerateCode() a synthetic _poolTypeInfos dictionary via
    // reflection, bypassing ScanExternalRefs/ScanInternalDeps/ComputeTotalSlots entirely -
    // those are covered separately by PoolModuleSlotMathTests.
    public class PoolModuleGenerateCodeTests
    {
        private static readonly Type InfoType = CodeGenModuleReflection.NestedType(typeof(PoolModule), "PoolTypeInfo");

        private static object Info(string typeName, string ns, int totalSlots)
            => CodeGenModuleReflection.BuildEntry(InfoType,
                ("Prefab", null), ("TypeName", typeName), ("TypeNamespace", ns),
                ("ExternalCount", 0), ("InternalDeps", new Dictionary<string, int>(StringComparer.Ordinal)),
                ("TotalSlots", totalSlots));

        private static PoolModule BuildModule(params (string typeName, string ns, int totalSlots)[] entries)
        {
            var dictType = typeof(Dictionary<,>).MakeGenericType(typeof(string), InfoType);
            var dict = (IDictionary)Activator.CreateInstance(dictType, StringComparer.Ordinal);
            foreach (var (typeName, ns, totalSlots) in entries)
                dict[typeName] = Info(typeName, ns, totalSlots);

            var module = new PoolModule();
            PrivateFieldAccess.SetField(module, "_poolTypeInfos", dict);
            return module;
        }

        [Test]
        public void GenerateCode_NoEligibleTypes_ReturnsStub()
        {
            string expected =
$@"// <auto-generated/>
// Generated by TsGenerator. Do not edit, changes will be overwritten.
// Regenerated automatically on domain reload, or manually via Tsvrc > Force Regenerate.

using UdonSharp;
using UnityEngine;

namespace {ScaffoldModule.CompiledNamespace}
{{
    public partial class {ScaffoldModule.CompiledClassName}
    {{
        public void _TsPoolStart()
        {{
        }}
    }}
}}
";

            GeneratedCodeAssert.AreEqual(expected, BuildModule().GenerateCode());
        }

        [Test]
        public void GenerateCode_ZeroTotalSlotsEntry_IsExcludedEvenIfConfigured()
        {
            var module = BuildModule(("StateManager", "Tsvrc.StateMachine", 0));

            string code = module.GenerateCode();

            StringAssert.DoesNotContain("StateManager", code);
        }

        [Test]
        public void GenerateCode_SlotFieldsAreNamedPerTypeAndIndex()
        {
            var module = BuildModule(("StateManager", "Tsvrc.StateMachine", 3));

            string code = module.GenerateCode();

            StringAssert.Contains("private StateManager _pool_StateManager_0;", code);
            StringAssert.Contains("private StateManager _pool_StateManager_1;", code);
            StringAssert.Contains("private StateManager _pool_StateManager_2;", code);
            StringAssert.DoesNotContain("_pool_StateManager_3;", code);
        }

        [Test]
        public void GenerateCode_TsBehaviourType_GetsTsConstructCallsPerSlot()
        {
            var module = BuildModule(("StateManager", "Tsvrc.StateMachine", 2));

            string code = module.GenerateCode();

            StringAssert.Contains("_pool_StateManager_0.TsConstruct(this);", code);
            StringAssert.Contains("_pool_StateManager_1.TsConstruct(this);", code);
        }

        [Test]
        public void GenerateCode_NonTsBehaviourType_SkipsConstructCallsEntirely()
        {
            var module = BuildModule(("Rigidbody", "UnityEngine", 2));

            string code = module.GenerateCode();

            StringAssert.Contains("private Rigidbody _pool_Rigidbody_0;", code);
            StringAssert.DoesNotContain("TsConstruct", code);
        }

        [Test]
        public void GenerateCode_MultipleTypes_OrderedAlphabeticallyByTypeName()
        {
            var module = BuildModule(
                ("Rigidbody", "UnityEngine", 1),
                ("StateManager", "Tsvrc.StateMachine", 1));

            string code = module.GenerateCode();

            int rb = code.IndexOf("_pool_Rigidbody_0", StringComparison.Ordinal);
            int sm = code.IndexOf("_pool_StateManager_0", StringComparison.Ordinal);
            Assert.Less(rb, sm);
        }
    }
}
