#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.Text;

namespace Tsvrc.Editor
{
    internal sealed class CsWriter
    {
        private const string IndentUnit = "    ";

        private readonly StringBuilder _sb = new StringBuilder();
        private int _depth = 0;

        internal void AutoGenHeader()
        {
            _sb.AppendLine("// <auto-generated/>");
            _sb.AppendLine("// Do NOT edit manually \u2014 re-run Tsvrc > Compile to update.");
        }

        internal void Usings(IEnumerable<string> namespaces)
        {
            foreach (var ns in namespaces)
                _sb.AppendLine($"using {ns};");
            _sb.AppendLine();
        }

        internal IDisposable Namespace(string name)
            => Block($"namespace {name}");

        internal IDisposable Class(string modifiers, string name, string baseClass, string attribute = null)
        {
            if (!string.IsNullOrEmpty(attribute))
                Line(attribute);
            return Block($"{modifiers} class {name} : {baseClass}");
        }

        internal IDisposable Block(string header = null)
        {
            if (!string.IsNullOrEmpty(header))
                Line(header);
            Raw(Indent() + "{");
            _depth++;
            return new BlockScope(this);
        }

        internal void Line(string code)
            => Raw(Indent() + code);

        internal void BlankLine()
            => _sb.AppendLine();

        internal void Summary(string text)
            => Line($"/// <summary>{text}</summary>");

        internal void Region(string name)
            => _sb.AppendLine($"{Indent()}#region {name}");

        internal void EndRegion()
            => _sb.AppendLine($"{Indent()}#endregion");

        internal IDisposable Method(string signature)
            => Block(signature);

        public override string ToString() => _sb.ToString();

        private void Raw(string line)
            => _sb.AppendLine(line);

        private string Indent()
        {
            if (_depth == 0) return "";
            var sb = new StringBuilder(_depth * IndentUnit.Length);
            for (int i = 0; i < _depth; i++) sb.Append(IndentUnit);
            return sb.ToString();
        }

        private void CloseBlock()
        {
            _depth--;
            Raw(Indent() + "}");
        }

        private sealed class BlockScope : IDisposable
        {
            private readonly CsWriter _writer;
            private bool _disposed;

            internal BlockScope(CsWriter writer) { _writer = writer; }

            public void Dispose()
            {
                if (_disposed) return;
                _disposed = true;
                _writer.CloseBlock();
            }
        }
    }
}
#endif
