using UnityEngine;

namespace Tsvrc.Config
{
    // Single scene-based config for everything PoolModule/GlobalModule/(future)Construct-
    // /FactoryModule need. Globals/Constructs are scene-object references, which only a
    // scene object can hold (a ScriptableObject asset cannot reference a scene object - a scene
    // object only has a fileID meaningful within its own scene file, no stable cross-file
    // address). PooledObjects/Factories are asset/prefab references, which a scene object can
    // also hold fine - only the reverse (asset -> scene) is impossible. So everything lives here
    // together rather than being split across an asset and a scene component.
    //
    // Auto-created/self-healed as a child of TsGenerated by ScaffoldModule, and always
    // tagged EditorOnly so it's stripped from the VRChat build - it's compile-time-only
    // configuration, never part of the generated runtime hierarchy. Plain MonoBehaviour, not
    // UdonSharpBehaviour: it's never compiled to Udon, only read by editor tooling.
    //
    // Deliberately NOT under an Editor/ folder and NOT wrapped in #if UNITY_EDITOR: scripts
    // under a folder named "Editor" are excluded from the runtime assembly entirely, and
    // GameObject.AddComponent silently fails for them - the component can be created here but
    // never actually attaches to a scene object. The EditorOnly tag on its GameObject (set by
    // ScaffoldModule) is what strips it from the VRChat build, not the script's location.
    public class TsConfig : MonoBehaviour
    {
        /// <summary>Scene objects exposed as named fields directly on the generated TsGenerated root.</summary>
        [Tooltip("Scene objects exposed as named fields directly on the generated TsGenerated root. Drag a GameObject or Component here. Organize into groups via Tsvrc > Configure.")]
        public TsGroupedEntry[] GlobalEntries;

        /// <summary>Nested groups organizing <see cref="GlobalEntries"/> for browsing. Purely organizational; does not affect generated field names.</summary>
        [Tooltip("Nested groups organizing GlobalEntries for browsing. Purely organizational - group names do not affect generated field names.")]
        public TsGroup[] GlobalGroups;

        /// <summary>The next unused id to assign in <see cref="GlobalGroups"/>.</summary>
        public int GlobalNextGroupId = 1;

        /// <summary>UdonSharpBehaviour prefabs to pool. Must be prefab assets, not scene objects.</summary>
        [Tooltip("UdonSharpBehaviour prefabs to pool. Must be prefab assets, not scene objects. Organize into groups via Tsvrc > Configure; groups are purely organizational.")]
        public TsGroupedEntry[] PoolEntries;

        /// <summary>Nested groups organizing <see cref="PoolEntries"/> for browsing. Purely organizational.</summary>
        [Tooltip("Nested groups organizing PoolEntries for browsing. Purely organizational.")]
        public TsGroup[] PoolGroups;

        /// <summary>The next unused id to assign in <see cref="PoolGroups"/>.</summary>
        public int PoolNextGroupId = 1;

        /// <summary>TsvrcBehaviours that are always active in the scene, not pooled. Constructed at startup.</summary>
        [Tooltip("TsvrcBehaviours that are always active in the scene, not pooled. Constructed at startup. Organize into groups via Tsvrc > Configure; groups are purely organizational.")]
        public TsGroupedEntry[] ConstructEntries;

        /// <summary>Nested groups organizing <see cref="ConstructEntries"/> for browsing. Purely organizational.</summary>
        [Tooltip("Nested groups organizing ConstructEntries for browsing. Purely organizational.")]
        public TsGroup[] ConstructGroups;

        /// <summary>The next unused id to assign in <see cref="ConstructGroups"/>.</summary>
        public int ConstructNextGroupId = 1;

        /// <summary>Prefabs to register for runtime instantiation (non-networked).</summary>
        [Tooltip("Prefabs to register for runtime instantiation (non-networked). Organize into nested groups via Tsvrc > Configure; a prefab's full group ancestor chain becomes its Create{...}(Transform parent) method name prefix.")]
        public TsGroupedEntry[] FactoryEntries;

        /// <summary>Nested groups organizing <see cref="FactoryEntries"/>. Each group's ancestor chain becomes a prefix on the generated Create method name for prefabs inside it.</summary>
        [Tooltip("Nested groups organizing FactoryEntries. Each group's (and its ancestors') name becomes a prefix on the generated Create method name for prefabs inside it.")]
        public TsGroup[] FactoryGroups;

        /// <summary>The next unused id to assign in <see cref="FactoryGroups"/>.</summary>
        public int FactoryNextGroupId = 1;

        /// <summary>
        /// When enabled, Global and Factory entries that no project script references (via
        /// <c>_ts.Name</c> or <c>CreateName(...)</c>) are left out of the generated output instead
        /// of always being included. Off by default.
        /// </summary>
        [Tooltip("Experimental: when enabled, Global and Factory entries not referenced by any project script (via _ts.Name or CreateName(...)) are excluded from generated output instead of always being included. Defaults to off.")]
        public bool TreeShakeUnused;

        /// <summary>
        /// Global/Factory names to always generate even when <see cref="TreeShakeUnused"/> is on
        /// and nothing currently references them. Use for reflection-based access, editor-only
        /// tooling, or entries you're about to wire up.
        /// </summary>
        [Tooltip("Global/Factory names to always generate even when TreeShakeUnused is on and no script currently references them - the escape valve for reflection-based access, editor-only tooling, or work in progress.")]
        public string[] ForceIncludeNames;
    }
}
