#if UNITY_EDITOR
using System.Collections.Generic;
using System.Text;

namespace Tsvrc.Editor
{
    internal static class TsvrcCodeBuilder
    {
        internal static string Build(TsvrcScanResult result)
        {
            var usings = new SortedSet<string> { "UdonSharp", "UnityEngine" };
            foreach (var group in result.Groups)
                foreach (var entry in group.Entries)
                    if (!string.IsNullOrEmpty(entry.Type.Namespace)) usings.Add(entry.Type.Namespace);

            var sb = new StringBuilder();
            sb.Append(Header(usings));
            foreach (var group in result.Groups)
                sb.Append(GenerateGroup(group));
            sb.AppendLine("}");
            sb.AppendLine("}");
            return sb.ToString();
        }

        // ── Sections ─────────────────────────────────────────────────────────────────────────

        private static string Header(SortedSet<string> usings)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("// Generated by: Tsvrc > Compile Singletons");
            sb.AppendLine("// Do NOT edit this file manually — re-run the compiler to update it.");
            sb.AppendLine();
            foreach (var ns in usings)
                sb.AppendLine($"using {ns};");
            sb.AppendLine();
            sb.AppendLine("namespace Tsvrc.Core.Compiled");
            sb.AppendLine("{");
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Auto-compiled Tsvrc context.");
            sb.AppendLine("/// Contains typed access to every entry registered in TsvrcInstance.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("public class CompiledTsvrc : UdonSharpBehaviour");
            sb.AppendLine("{");
            return sb.ToString();
        }

        private static string GenerateGroup(TsvrcGroup group)
        {
            switch (group.Kind)
            {
                case TsvrcGroupKind.Singleton: return SingletonFields(group);
                case TsvrcGroupKind.Behaviour: return BehaviourSection(group);
                default: return "";
            }
        }

        // ── Group generators ─────────────────────────────────────────────────────────────────

        private static string SingletonFields(TsvrcGroup group)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"    // {group.Label}");
            foreach (var entry in group.Entries)
            {
                sb.AppendLine($"    /// <summary>Tsvrc singleton — auto-assigned by TsvrcInstance.</summary>");
                sb.AppendLine($"    public {entry.Type.Name} {entry.FieldName};");
            }
            return sb.ToString();
        }

        private static string BehaviourSection(TsvrcGroup group)
        {
            var sb = new StringBuilder();

            // [SerializeField] fields + Start() — only for entries whose factory is called
            var used = new List<TsvrcEntry>();
            foreach (var entry in group.Entries)
                if (entry.FactoryUsed) used.Add(entry);

            if (used.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine($"    // {group.Label} — kept inactive in the scene.");
                sb.AppendLine("    // Inactive GameObjects consume zero CPU: no Update, no UdonSharp ticks, no rendering.");
                foreach (var entry in used)
                    sb.AppendLine($"    [SerializeField] private {entry.Type.Name} _{Low(entry.FieldName)};");

                sb.AppendLine();
                sb.AppendLine("    protected void Start()");
                sb.AppendLine("    {");
                foreach (var entry in used)
                    sb.AppendLine($"        _{Low(entry.FieldName)}.gameObject.SetActive(false);");
                sb.AppendLine("    }");
            }

            sb.AppendLine();
            foreach (var entry in group.Entries)
                sb.Append(FactoryMethod(entry));

            return sb.ToString();
        }

        // ── Templates ────────────────────────────────────────────────────────────────────────

        private static string FactoryMethod(TsvrcEntry entry)
        {
            string name = entry.Type.Name;
            string field = entry.FieldName;
            string lower = Low(field);
            string doc = $"    /// <summary>Instantiates a new active <see cref=\"{name}\"/> from its inactive template.</summary>";

            if (entry.FactoryUsed) return
$@"{doc}
    public {name} Create{field}()
    {{
        var instance = Instantiate(_{lower}.gameObject);
        instance.SetActive(true);
        var behaviour = instance.GetComponent<{name}>();
        behaviour.TsConstruct(this);
        return behaviour;
    }}
";
            return
$@"{doc}
    public {name} Create{field}()
    {{
        Debug.LogError(""[CompiledTsvrc] {name} has no Create{name}() call site. Remove it from TsvrcInstance.Behaviours or call it somewhere."");
        return null;
    }}
";
        }

        // ── Helpers ──────────────────────────────────────────────────────────────────────────

        private static string Low(string s) =>
            string.IsNullOrEmpty(s) ? s : char.ToLowerInvariant(s[0]) + s.Substring(1);
    }
}
#endif
