#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.Text;

namespace Tsvrc.Editor
{
    internal static class TsvrcCodeBuilder
    {
        private const string AutoGenHeader =
            "// <auto-generated/>\n" +
            "// Do NOT edit manually — re-run Tsvrc > Compile to update.\n";

        // ── CompiledTsvrc : pure typed accessor ──────────────────────────────────────────────

        internal static string Build(TsvrcScanResult result)
        {
            var usings = CollectUsings(result, kindFilter: TsvrcGroupKind.Singleton);

            var sb = new StringBuilder();
            sb.Append(AutoGenHeader);
            sb.AppendLine();
            AppendUsings(sb, usings);
            sb.AppendLine("namespace Tsvrc.Core.Compiled {");
            sb.AppendLine("public class CompiledTsvrc : UdonSharpBehaviour {");

            foreach (var group in result.Groups)
                if (group.Kind == TsvrcGroupKind.Singleton)
                    foreach (var entry in group.Entries)
                    {
                        sb.AppendLine($"    /// <summary>Tsvrc singleton — set by CompiledTsvrcInstance.</summary>");
                        sb.AppendLine($"    [SerializeField] public {entry.Type.Name} {entry.FieldName};");
                    }

            sb.AppendLine("} }");
            return sb.ToString();
        }

        // ── CompiledTsvrcInstance : lifecycle bootstrap ──────────────────────────────────────

        internal static string BuildInstance(TsvrcScanResult result)
        {
            var usings = CollectUsings(result);
            usings.Add("Tsvrc.Core.Compiled");

            var startupLines = new List<string>();

            // TsConstruct TsvrcBehaviour singletons
            foreach (var group in result.Groups)
                if (group.Kind == TsvrcGroupKind.Singleton)
                    foreach (var entry in group.Entries)
                        if (entry.IsTsvrcBehaviour)
                            startupLines.Add($"_ts.{entry.FieldName}.TsConstruct(_ts);");

            // Disable behaviour templates
            var usedBehaviours = new List<TsvrcEntry>();
            foreach (var group in result.Groups)
                if (group.Kind == TsvrcGroupKind.Behaviour)
                    foreach (var entry in group.Entries)
                        if (entry.FactoryUsed)
                        {
                            usedBehaviours.Add(entry);
                            startupLines.Add($"_{Low(entry.FieldName)}.gameObject.SetActive(false);");
                        }

            var sb = new StringBuilder();
            sb.Append(AutoGenHeader);
            sb.AppendLine();
            AppendUsings(sb, usings);
            sb.AppendLine("namespace Tsvrc.Core.Compiled {");
            sb.AppendLine("public class CompiledTsvrcInstance : UdonSharpBehaviour {");
            sb.AppendLine("    [SerializeField] private CompiledTsvrc _ts;");

            // [SerializeField] fields for behaviour templates
            if (usedBehaviours.Count > 0)
            {
                sb.AppendLine();
                foreach (var entry in usedBehaviours)
                    sb.AppendLine($"    [SerializeField] private {entry.Type.Name} _{Low(entry.FieldName)};");
            }

            // Start()
            if (startupLines.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine("    protected void Start() {");
                foreach (var line in startupLines)
                    sb.AppendLine($"        {line}");
                sb.AppendLine("    }");
            }

            // Factory methods
            foreach (var group in result.Groups)
                if (group.Kind == TsvrcGroupKind.Behaviour)
                    foreach (var entry in group.Entries)
                        sb.Append(FactoryMethod(entry));

            sb.AppendLine("} }");
            return sb.ToString();
        }

        // ── Templates ────────────────────────────────────────────────────────────────────────

        private static string FactoryMethod(TsvrcEntry entry)
        {
            string name = entry.Type.Name;
            string field = entry.FieldName;
            string lower = Low(field);
            string doc = $"    /// <summary>Instantiates a new <see cref=\"{name}\"/> from its inactive template.</summary>";

            if (entry.FactoryUsed) return
$@"
{doc}
    public {name} Create{field}() {{
        var go = Instantiate(_{lower}.gameObject);
        go.SetActive(true);
        var b = go.GetComponent<{name}>();
        b.TsConstruct(_ts);
        return b;
    }}
";
            return
$@"
{doc}
    public {name} Create{field}() {{
        Debug.LogError(""[CompiledTsvrcInstance] {name} has no Create{name}() call site."");
        return null;
    }}
";
        }

        // ── Helpers ──────────────────────────────────────────────────────────────────────────

        private static SortedSet<string> CollectUsings(TsvrcScanResult result, TsvrcGroupKind? kindFilter = null)
        {
            var usings = new SortedSet<string> { "UdonSharp", "UnityEngine" };
            foreach (var group in result.Groups)
            {
                if (kindFilter.HasValue && group.Kind != kindFilter.Value) continue;
                foreach (var entry in group.Entries)
                    if (!string.IsNullOrEmpty(entry.Type.Namespace)) usings.Add(entry.Type.Namespace);
            }
            return usings;
        }

        private static void AppendUsings(StringBuilder sb, SortedSet<string> usings)
        {
            foreach (var ns in usings) sb.AppendLine($"using {ns};");
            sb.AppendLine();
        }

        private static string Low(string s) =>
            string.IsNullOrEmpty(s) ? s : char.ToLowerInvariant(s[0]) + s.Substring(1);
    }
}
#endif
