#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.Linq;
using Tsvrc.Utils;
using UdonSharp;
using UdonSharpEditor;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace Tsvrc.Editor.V2
{
    internal class ScaffoldModule : TsvrcModule
    {
        internal const string CompiledNamespace = "Tsvrc.Core.Generated";
        internal const string CompiledClassName = "TsvrcGenerated";
        internal const string PoolClassName = "TsvrcPoolBehaviour";
        internal const string TranslationClassName = "TsvrcTranslationBehaviour";
        internal const string SingletonClassName = "TsvrcSingletonBehaviour";

        private const string ScaffoldFilePath = "Assets/TsvrcGenerated/TsvrcGenerated.cs";
        private const string GeneratedAssetPath = "Assets/TsvrcGenerated/TsvrcGenerated.asset";
        private const string PoolBehaviourFilePath = "Assets/TsvrcGenerated/TsvrcPoolBehaviour.cs";
        private const string PoolBehaviourAssetPath = "Assets/TsvrcGenerated/TsvrcPoolBehaviour.asset";
        private const string TranslationBehaviourFilePath = "Assets/TsvrcGenerated/TsvrcTranslationBehaviour.cs";
        private const string TranslationBehaviourAssetPath = "Assets/TsvrcGenerated/TsvrcTranslationBehaviour.asset";
        private const string SingletonBehaviourFilePath = "Assets/TsvrcGenerated/TsvrcSingletonBehaviour.cs";
        private const string SingletonBehaviourAssetPath = "Assets/TsvrcGenerated/TsvrcSingletonBehaviour.asset";
        private const string MemoryScriptPath = "Assets/Tsvrc/Scripts/Utils/TsMemory.cs";
        private const string MemoryAssetPath = "Assets/Tsvrc/Scripts/Utils/TsMemory.asset";

        internal override string FileName => "TsvrcGenerated.cs";

        internal override void LoadConfig() { }

        internal override string GenerateCode() =>
$@"// <auto-generated/>
// Generated by Tsvrc. Do not edit.
using Tsvrc.Core;
using Tsvrc.Utils;
using UdonSharp;
using UnityEngine;

namespace {CompiledNamespace}
{{
    [AddComponentMenu("""")]
    public class {CompiledClassName} : UdonSharpBehaviour
    {{
        [SerializeField] private {PoolClassName} _pool;
        [SerializeField] private {TranslationClassName} _translation;
        [ReadOnly] [SerializeField] private TsvrcInstance _instance;
        [SerializeField] private TsMemory _memory;
        [SerializeField] private {SingletonClassName} _singleton;

        void Start() {{ }}

        public TsvrcInstance Instance => _instance;
        public TsMemory Memory => _memory;
        public {SingletonClassName} Singleton => _singleton;
        public void SetLanguage(Language lang) {{ _translation.SetLanguage(lang); }}
        public string Translate(string key) {{ return _translation.Translate(key); }}
        public string Translate(string key, string param) {{ return _translation.Translate(key, param); }}
        public void SubscribeLanguageChanged(UdonSharpBehaviour listener, string callback) {{ _translation.SubscribeLanguageChanged(listener, callback); }}
    }}
}}";

        internal override bool AfterFilesStable()
        {
            EnsureUdonSharpProgramAsset(ScaffoldFilePath, GeneratedAssetPath);
            EnsureUdonSharpProgramAsset(PoolBehaviourFilePath, PoolBehaviourAssetPath);
            EnsureUdonSharpProgramAsset(TranslationBehaviourFilePath, TranslationBehaviourAssetPath);
            EnsureUdonSharpProgramAsset(MemoryScriptPath, MemoryAssetPath);
            EnsureUdonSharpProgramAsset(SingletonBehaviourFilePath, SingletonBehaviourAssetPath);
            var root = EnsureRootSceneObject();
            if (root != null)
            {
                EnsureChildSceneObject("TsvrcPool", FindPoolType(), root);
                EnsureChildSceneObject("TsvrcTranslation", FindTranslationType(), root);
                EnsureChildSceneObject("TsvrcMemory", typeof(TsMemory), root);
                EnsureChildSceneObject("TsvrcSingleton", FindSingletonType(), root);
                EnsureChildSceneObject("TsvrcConfig", typeof(TsvrcConfig), root, isUdonSharp: false, editorOnly: true);
            }
            return false;
        }

        internal override bool OnSceneHierarchyChanged()
        {
            var compiledType = FindCompiledType();
            if (compiledType == null) return false;

            var instances = UnityEngine.Object.FindObjectsOfType(compiledType, true);
            if (instances.Length != 1) return true;

            var root = ((Component)instances[0]).transform;
            if (root.Find("TsvrcPool") == null) return true;
            if (root.Find("TsvrcTranslation") == null) return true;
            if (root.Find("TsvrcMemory") == null) return true;
            if (root.Find("TsvrcSingleton") == null) return true;
            if (root.Find("TsvrcConfig") == null) return true;
            return false;
        }

        internal override void Wire()
        {
            var compiledType = FindCompiledType();
            var poolType = FindPoolType();
            var transType = FindTranslationType();
            if (compiledType == null || poolType == null || transType == null) return;

            var singletonType = FindSingletonType();

            var root = (Component)UnityEngine.Object.FindObjectOfType(compiledType, true);
            var pool = (Component)UnityEngine.Object.FindObjectOfType(poolType, true);
            var trans = (Component)UnityEngine.Object.FindObjectOfType(transType, true);
            var memory = (Component)UnityEngine.Object.FindObjectOfType(typeof(TsMemory), true);
            var singleton = singletonType != null ? (Component)UnityEngine.Object.FindObjectOfType(singletonType, true) : null;
            if (root == null || pool == null || trans == null) return;

            var so = new SerializedObject(root);
            so.FindProperty("_pool").objectReferenceValue = pool;
            so.FindProperty("_translation").objectReferenceValue = trans;
            so.FindProperty("_memory").objectReferenceValue = memory;
            so.FindProperty("_singleton").objectReferenceValue = singleton;
            if (so.ApplyModifiedProperties())
                EditorSceneManager.MarkSceneDirty(root.gameObject.scene);
        }

        internal static Type FindCompiledType() => FindType(CompiledClassName);
        internal static Type FindPoolType() => FindType(PoolClassName);
        internal static Type FindTranslationType() => FindType(TranslationClassName);
        internal static Type FindSingletonType() => FindType(SingletonClassName);

        private static Type FindType(string className)
        {
            var fullName = CompiledNamespace + "." + className;
            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                var type = assembly.GetType(fullName);
                if (type != null) return type;
            }
            return null;
        }

        private static void EnsureUdonSharpProgramAsset(string scriptPath, string assetPath)
        {
            var monoScript = AssetDatabase.LoadAssetAtPath<MonoScript>(scriptPath);
            if (monoScript == null) return;

            var programAsset = AssetDatabase.LoadAssetAtPath<UdonSharpProgramAsset>(assetPath);
            if (programAsset == null)
            {
                programAsset = ScriptableObject.CreateInstance<UdonSharpProgramAsset>();
                programAsset.sourceCsScript = monoScript;
                AssetDatabase.CreateAsset(programAsset, assetPath);
                AssetDatabase.SaveAssetIfDirty(programAsset);
                Debug.Log($"[TsvrcGenerator] Created program asset at {assetPath}");
                return;
            }

            if (programAsset.sourceCsScript != monoScript)
            {
                programAsset.sourceCsScript = monoScript;
                EditorUtility.SetDirty(programAsset);
                AssetDatabase.SaveAssetIfDirty(programAsset);
            }
        }

        private static Component EnsureRootSceneObject()
        {
            var compiledType = FindCompiledType();
            if (compiledType == null) return null;

            var instances = UnityEngine.Object.FindObjectsOfType(compiledType, true)
                .Cast<Component>().ToList();

            for (int i = instances.Count - 1; i >= 1; i--)
            {
                var duplicate = instances[i].gameObject;
                var scene = duplicate.scene;
                Undo.DestroyObjectImmediate(duplicate);
                EditorSceneManager.MarkSceneDirty(scene);
            }

            if (instances.Count > 0) return instances[0];

            var namedObjects = FindSceneGameObjects(CompiledClassName);
            if (namedObjects.Count > 0)
            {
                for (int i = namedObjects.Count - 1; i >= 1; i--)
                {
                    var scene = namedObjects[i].scene;
                    Undo.DestroyObjectImmediate(namedObjects[i]);
                    EditorSceneManager.MarkSceneDirty(scene);
                }
                UdonSharpUndo.AddComponent(namedObjects[0], compiledType);
                EditorSceneManager.MarkSceneDirty(namedObjects[0].scene);
                return namedObjects[0].GetComponent(compiledType) as Component;
            }

            var go = new GameObject(CompiledClassName);
            go.transform.SetSiblingIndex(0);
            Undo.RegisterCreatedObjectUndo(go, $"Create {CompiledClassName}");
            UdonSharpUndo.AddComponent(go, compiledType);
            EditorSceneManager.MarkSceneDirty(SceneManager.GetActiveScene());
            Debug.Log($"[TsvrcGenerator] Created {CompiledClassName} in scene.");
            return go.GetComponent(compiledType) as Component;
        }

        // isUdonSharp selects AddComponent path: UdonSharpUndo.AddComponent is required for
        // UdonSharpBehaviour types (it also sets up the hidden backing UdonBehaviour); plain
        // MonoBehaviours (e.g. TsvrcConfig, never compiled to Udon) use the regular Undo
        // API instead. editorOnly enforces (and self-heals) the "EditorOnly" tag on the child's
        // GameObject so it's guaranteed stripped from the VRChat build - used for compile-time-
        // only config holders that must never ship as part of the generated runtime hierarchy.
        private static void EnsureChildSceneObject(string childName, Type componentType, Component root, bool isUdonSharp = true, bool editorOnly = false)
        {
            if (componentType == null) return;

            var existing = root.transform.Find(childName);
            GameObject childGo;

            if (existing == null)
            {
                childGo = new GameObject(childName);
                Undo.RegisterCreatedObjectUndo(childGo, $"Create {childName}");
                childGo.transform.SetParent(root.transform, false);
                AddChildComponent(childGo, componentType, isUdonSharp);
                EditorSceneManager.MarkSceneDirty(root.gameObject.scene);
                Debug.Log($"[TsvrcGenerator] Created {childName} child under {CompiledClassName}.");
            }
            else
            {
                childGo = existing.gameObject;
                if (existing.GetComponent(componentType) == null)
                {
                    AddChildComponent(childGo, componentType, isUdonSharp);
                    EditorSceneManager.MarkSceneDirty(root.gameObject.scene);
                }
            }

            if (editorOnly && childGo.tag != "EditorOnly")
            {
                childGo.tag = "EditorOnly";
                EditorSceneManager.MarkSceneDirty(root.gameObject.scene);
            }
        }

        private static void AddChildComponent(GameObject go, Type componentType, bool isUdonSharp)
        {
            if (isUdonSharp)
            {
                // UdonSharpUndo.AddComponent is required for UdonSharpBehaviour types - it also
                // sets up the hidden backing UdonBehaviour, which a plain AddComponent would miss.
                UdonSharpUndo.AddComponent(go, componentType);
                return;
            }

            // Undo.AddComponent only has a generic <T> overload, which can't be used with a
            // runtime Type. Add directly and register the result for undo instead.
            var component = go.AddComponent(componentType);
            Undo.RegisterCreatedObjectUndo(component, $"Add {componentType.Name}");
        }

        private static List<GameObject> FindSceneGameObjects(string name)
        {
            var result = new List<GameObject>();
            for (int i = 0; i < SceneManager.sceneCount; i++)
            {
                var scene = SceneManager.GetSceneAt(i);
                if (!scene.isLoaded) continue;
                foreach (var root in scene.GetRootGameObjects())
                    CollectInHierarchy(root, name, result);
            }
            return result;
        }

        private static void CollectInHierarchy(GameObject root, string name, List<GameObject> result)
        {
            if (root.name == name) result.Add(root);
            foreach (Transform child in root.transform)
                CollectInHierarchy(child.gameObject, name, result);
        }
    }
}
#endif
