#if UNITY_EDITOR
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using UdonSharp;
using UdonSharpEditor;
using Tsvrc.Config;
using Tsvrc.Core;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace Tsvrc.Editor
{
    // Manages the TsGenerated root GameObject and its UdonSharpProgramAsset. This
    // module's generated file (TsGenerated.cs) declares the partial class that all
    // other modules extend; it must always be written first and compiled before any
    // Wire() pass can locate the root object via FindCompiledType().
    internal class ScaffoldModule : TsModule
    {
        internal static string CompiledNamespace => TsPaths.CompiledNamespace;
        internal static string CompiledClassName => TsPaths.CompiledClassName;

        // Always project-Assets-rooted (or the test-redirected scratch equivalent, see
        // TsPaths), never package-relative. TsPaths.ScaffoldScriptPath/AssetPath default to
        // null, meaning "derive from GeneratedFolder + CompiledClassName", the normal case
        // for production and most tests alike. Only overridden explicitly by tests that need the
        // scaffold script to live somewhere other than the generated folder (see
        // CompiledRootFixture / ScaffoldModuleWireTests).
        // internal, not private: shared with TsWindow and TsDomainReloadHandler, so both read the
        // exact same "does the scaffold file genuinely exist" fact this module's writes are the
        // source of truth for, rather than each re-deriving the path itself.
        internal static string ScaffoldFilePath => TsPaths.ScaffoldScriptPath ?? $"{TsPaths.GeneratedFolder}/{TsPaths.CompiledClassName}.cs";
        private static string GeneratedAssetPath => TsPaths.ScaffoldAssetPath ?? $"{TsPaths.GeneratedFolder}/{TsPaths.CompiledClassName}.asset";

        // Cheap, file-existence-only check (not a real parse) for whether a prior bootstrap ever
        // completed.
        internal static bool ScaffoldFileExists() => System.IO.File.Exists(TsPaths.ToFullPath(ScaffoldFilePath));

        internal override string FileName => TsPaths.CompiledClassName + ".cs";

        internal override IEnumerable<string> WatchedAssets() => new[] { GeneratedAssetPath };

        internal override void LoadConfig() { }

        // World scripts must extend the generated shadow class below instead of the
        // corresponding Tsvrc framework class directly (e.g. `MolInstance : TsInstance`, where
        // `TsInstance` is the generated shadow of the framework's `Instance` class). Each entry
        // hides the inherited `_ts` field with a same-named property retyped to the concrete
        // {CompiledClassName}, so every project-specific global/pool/construct/factory member
        // becomes visible through `_ts` with no cast. The set of base types is discovered via
        // reflection, not hardcoded here: any class in Tsvrc.Runtime tagged with
        // [TsWorldExtensionPoint(generatedName)] gets a shadow generated under that name, so
        // adding a new one is a one-line attribute on the framework class itself, not a
        // ScaffoldModule edit. Sorted by generated name for deterministic output.
        private static IEnumerable<(string GeneratedName, string BaseTypeFullName)> DiscoverWorldBaseTypes()
        {
            return typeof(TsvrcBehaviour).Assembly.GetTypes()
                .Where(t => t.IsClass && t.IsDefined(typeof(TsWorldExtensionPointAttribute), inherit: false))
                .Select(t => (
                    GeneratedName: t.GetCustomAttribute<TsWorldExtensionPointAttribute>().GeneratedName,
                    BaseTypeFullName: "global::" + t.FullName))
                .OrderBy(x => x.GeneratedName, StringComparer.Ordinal);
        }

        internal override string GenerateCode()
        {
            var worldBases = new StringBuilder();
            foreach (var (generatedName, baseTypeFullName) in DiscoverWorldBaseTypes())
            {
                worldBases.Append($@"
    public abstract class {generatedName} : {baseTypeFullName}
    {{
        protected new {CompiledClassName} _ts => ({CompiledClassName})base._ts;
    }}
");
            }

            return
$@"// <auto-generated/>
// Generated by TsGenerator. Do not edit, changes will be overwritten.
// Regenerated automatically on domain reload, or manually via Tsvrc > Force Regenerate.
using UdonSharp;
using UnityEngine;

namespace {CompiledNamespace}
{{
    [UdonBehaviourSyncMode(BehaviourSyncMode.None)]
    [AddComponentMenu("""")]
    public partial class {CompiledClassName} : TsRoot
    {{
        void Start()
        {{
            _TsLogStart();
            _TsMemoryStart();
            _TsGlobalStart();
            _TsPoolStart();
            _TsConstructStart();
            _TsInstanceStart();
        }}
    }}
{worldBases}}}";
        }

        internal override bool AfterFilesStable()
        {
            bool programAssetMissing = AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(GeneratedAssetPath) == null;
            EnsureUdonSharpProgramAsset(ScaffoldFilePath, GeneratedAssetPath);
            var root = EnsureRootSceneObject();
            if (root != null)
            {
                EnsureChildSceneObject("TsConfig", typeof(TsConfig), root, isUdonSharp: false, editorOnly: true);
                AutoLinkSceneIfUnconfigured(root);
            }

            // fieldDefinitions order in the program asset is non-deterministic across compilations,
            // causing unnecessary file changes on every domain reload, so normalize to sorted order.
            bool normalized = false;
            foreach (var guid in AssetDatabase.FindAssets("t:UdonSharpProgramAsset", new[] { TsPaths.GeneratedFolder }))
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                normalized |= NormalizeProgramAsset(AssetDatabase.LoadAssetAtPath<UdonSharpProgramAsset>(path));
            }

            return programAssetMissing || normalized;
        }

        // Sorts fieldDefinitions to a stable order. Returns true if the asset was modified and saved.
        internal static bool NormalizeProgramAsset(UdonSharpProgramAsset asset)
        {
            if (asset == null) return false;

            FieldInfo fi = null;
            for (var t = asset.GetType(); t != null && fi == null; t = t.BaseType)
                fi = t.GetField("fieldDefinitions", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
            if (fi == null) return false;

            if (fi.GetValue(asset) is not IDictionary fieldDefs || fieldDefs.Count == 0) return false;

            string prevKey = null;
            bool needsSort = false;
            foreach (DictionaryEntry e in fieldDefs)
            {
                string key = e.Key as string;
                if (prevKey != null && string.Compare(prevKey, key, StringComparison.Ordinal) > 0)
                {
                    needsSort = true;
                    break;
                }
                prevKey = key;
            }
            if (!needsSort) return false;

            var pairs = new List<(string key, object val)>();
            foreach (DictionaryEntry e in fieldDefs)
                pairs.Add(((string)e.Key, e.Value));
            pairs.Sort((a, b) => string.Compare(a.key, b.key, StringComparison.Ordinal));

            var sorted = (IDictionary)Activator.CreateInstance(fieldDefs.GetType());
            foreach (var (k, v) in pairs) sorted[k] = v;

            fi.SetValue(asset, sorted);
            EditorUtility.SetDirty(asset);
            AssetDatabase.SaveAssetIfDirty(asset);
            return true;
        }

        internal override bool OnSceneHierarchyChanged()
        {
            var compiledType = FindCompiledType();
            if (compiledType == null) return false;

            // Scoped to the linked scene, same as every other lookup in this module: an unrelated
            // compiled-type instance in an additively-loaded scene must never gate this module's
            // own rerun scheduling.
            var instances = TsLinkedScene.FindAllType(compiledType);
            if (instances.Count != 1) return true;

            var root = instances[0].transform;
            if (root.Find("TsConfig") == null) return true;
            return false;
        }

        internal static Type FindCompiledType() => FindType(CompiledClassName);

        private static Type FindType(string className)
        {
            var fullName = CompiledNamespace + "." + className;
            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                var type = assembly.GetType(fullName);
                if (type != null) return type;
            }
            return null;
        }

        internal static bool EnsureUdonSharpProgramAsset(string scriptPath, string assetPath)
        {
            var monoScript = AssetDatabase.LoadAssetAtPath<MonoScript>(scriptPath);
            if (monoScript == null) return false;

            var programAsset = AssetDatabase.LoadAssetAtPath<UdonSharpProgramAsset>(assetPath);
            if (programAsset == null)
            {
                programAsset = ScriptableObject.CreateInstance<UdonSharpProgramAsset>();
                programAsset.sourceCsScript = monoScript;
                AssetDatabase.CreateAsset(programAsset, assetPath);
                AssetDatabase.SaveAssetIfDirty(programAsset);
                Debug.Log($"[TsGenerator] Created program asset at {assetPath}");
                return true;
            }

            if (programAsset.sourceCsScript != monoScript)
            {
                programAsset.sourceCsScript = monoScript;
                EditorUtility.SetDirty(programAsset);
                AssetDatabase.SaveAssetIfDirty(programAsset);
            }
            return true;
        }

        // The first successful bootstrap unambiguously identifies which scene the user means, so
        // it auto-links it rather than leaving the corruption-safety net TsLinkedScene provides
        // silently opt-in forever. A no-op once anything is already linked, including by an
        // earlier call within this same pass: once a scene is linked, RunCore's own
        // IsConfiguredButNotLoaded guard refuses to touch any other scene, so a second scene can
        // never silently grow its own competing scaffold.
        private static void AutoLinkSceneIfUnconfigured(Component root)
        {
            if (TsLinkedScene.IsConfigured) return;
            string scenePath = root.gameObject.scene.path;
            if (string.IsNullOrEmpty(scenePath)) return; // an unsaved scene has no path to link to yet
            TsLinkedScene.ScenePath = scenePath;
            Debug.Log($"[TsGenerator] Linked Tsvrc to scene '{scenePath}'.");
        }

        private static Component EnsureRootSceneObject()
        {
            var compiledType = FindCompiledType();
            if (compiledType == null) return null;

            // Scoped to the linked scene: an extra compiled-type instance in an unrelated
            // additively-loaded scene must never be found (and destroyed as a "duplicate") here.
            var instances = TsLinkedScene.FindAllType(compiledType);

            // Logged before destroying, naming both which path survives and which are removed, so
            // a puzzled "where did my other copy's settings go" (e.g. after a Ctrl+D duplicate)
            // has a trail to follow in the Console.
            if (instances.Count > 1)
                Debug.LogWarning($"[TsGenerator] Multiple {CompiledClassName} instances found. Keeping " +
                    $"'{GameObjectPath(instances[0].gameObject)}', destroying " +
                    $"{string.Join(", ", instances.Skip(1).Select(c => $"'{GameObjectPath(c.gameObject)}'"))}.");

            for (int i = instances.Count - 1; i >= 1; i--)
            {
                var duplicate = instances[i].gameObject;
                var scene = duplicate.scene;
                Undo.DestroyObjectImmediate(duplicate);
                EditorSceneManager.MarkSceneDirty(scene);
            }

            if (instances.Count > 0) return instances[0];

            var namedObjects = FindSceneGameObjects(CompiledClassName);
            if (namedObjects.Count > 0)
            {
                for (int i = namedObjects.Count - 1; i >= 1; i--)
                {
                    var scene = namedObjects[i].scene;
                    Undo.DestroyObjectImmediate(namedObjects[i]);
                    EditorSceneManager.MarkSceneDirty(scene);
                }
                UdonSharpUndo.AddComponent(namedObjects[0], compiledType);
                EditorSceneManager.MarkSceneDirty(namedObjects[0].scene);
                return namedObjects[0].GetComponent(compiledType);
            }

            var go = new GameObject(CompiledClassName);
            go.transform.SetSiblingIndex(0);
            Undo.RegisterCreatedObjectUndo(go, $"Create {CompiledClassName}");
            UdonSharpUndo.AddComponent(go, compiledType);
            EditorSceneManager.MarkSceneDirty(SceneManager.GetActiveScene());
            Debug.Log($"[TsGenerator] Created {CompiledClassName} in scene.");
            return go.GetComponent(compiledType);
        }

        // isUdonSharp selects AddComponent path: UdonSharpUndo.AddComponent is required for
        // UdonSharpBehaviour types (it also sets up the hidden backing UdonBehaviour); plain
        // MonoBehaviours (e.g. TsConfig, never compiled to Udon) use the regular Undo
        // API instead. editorOnly enforces (and self-heals) the "EditorOnly" tag on the child's
        // GameObject so it's guaranteed stripped from the VRChat build. Used for compile-time-
        // only config holders that must never ship as part of the generated runtime hierarchy.
        internal static void EnsureChildSceneObject(string childName, Type componentType, Component root, bool isUdonSharp = true, bool editorOnly = false)
        {
            if (componentType == null) return;

            var existing = root.transform.Find(childName);
            GameObject childGo;

            if (existing == null)
            {
                // Before creating a brand-new, empty child, check whether an instance of this
                // component already exists elsewhere in the linked scene - it may have been
                // dragged out from under the root rather than deleted. Reparenting it back
                // preserves whatever data it holds instead of creating a second, empty sibling and
                // leaving the real one orphaned. Also renamed to childName, so the next pass's
                // root.transform.Find(childName) finds it directly. Not restricted to "not already
                // a child of root": if it's a child of root but misnamed, reparenting to the same
                // parent is a harmless no-op and the rename below is what actually fixes it.
                var elsewhere = TsLinkedScene.FindType(componentType);
                if (elsewhere != null && elsewhere.gameObject != root.gameObject)
                {
                    childGo = elsewhere.gameObject;
                    Undo.SetTransformParent(childGo.transform, root.transform, $"Reparent {childName}");
                    if (childGo.name != childName)
                    {
                        Undo.RecordObject(childGo, $"Rename {childName}");
                        childGo.name = childName;
                    }
                    EditorSceneManager.MarkSceneDirty(root.gameObject.scene);
                    Debug.Log($"[TsGenerator] Found an existing {childName} outside {CompiledClassName}'s hierarchy and moved it back, instead of creating a new empty one.");
                }
                else
                {
                    childGo = new GameObject(childName);
                    Undo.RegisterCreatedObjectUndo(childGo, $"Create {childName}");
                    childGo.transform.SetParent(root.transform, false);
                    AddChildComponent(childGo, componentType, isUdonSharp);
                    EditorSceneManager.MarkSceneDirty(root.gameObject.scene);
                    Debug.Log($"[TsGenerator] Created {childName} child under {CompiledClassName}.");
                }
            }
            else
            {
                childGo = existing.gameObject;
                if (existing.GetComponent(componentType) == null)
                {
                    AddChildComponent(childGo, componentType, isUdonSharp);
                    EditorSceneManager.MarkSceneDirty(root.gameObject.scene);
                }
            }

            if (editorOnly && !childGo.CompareTag("EditorOnly"))
            {
                childGo.tag = "EditorOnly";
                EditorSceneManager.MarkSceneDirty(root.gameObject.scene);
            }
        }

        // "Root/Child/Grandchild" style path, for naming a specific GameObject in a diagnostic
        // without requiring the reader to go hunting for it in the Hierarchy. internal, not
        // private: also used by TsGenerator's own ambiguous-TsConfig diagnostic.
        internal static string GameObjectPath(GameObject go)
        {
            var segments = new List<string>();
            for (var t = go.transform; t != null; t = t.parent)
                segments.Add(t.name);
            segments.Reverse();
            return string.Join("/", segments);
        }

        private static void AddChildComponent(GameObject go, Type componentType, bool isUdonSharp)
        {
            if (isUdonSharp)
            {
                UdonSharpUndo.AddComponent(go, componentType);
                return;
            }

            // Undo.AddComponent only has a generic <T> overload, which can't be used with a
            // runtime Type. Add directly and register the result for undo instead.
            var component = go.AddComponent(componentType);
            Undo.RegisterCreatedObjectUndo(component, $"Add {componentType.Name}");
        }

        // Scoped to the linked scene once one is configured, exactly like every other lookup in
        // this module: an unrelated same-named GameObject in an additively-loaded scene must
        // never be found (and its duplicates destroyed) by this scan. Falls back to scanning
        // every loaded scene only when nothing is configured yet.
        private static List<GameObject> FindSceneGameObjects(string name)
        {
            var result = new List<GameObject>();
            foreach (var scene in ScenesToScan())
                foreach (var root in scene.GetRootGameObjects())
                    CollectInHierarchy(root, name, result);
            return result;
        }

        private static IEnumerable<Scene> ScenesToScan()
        {
            if (TsLinkedScene.IsConfigured)
            {
                var linked = TsLinkedScene.FindLoadedScene();
                if (linked.HasValue) yield return linked.Value;
                yield break;
            }
            for (int i = 0; i < SceneManager.sceneCount; i++)
            {
                var scene = SceneManager.GetSceneAt(i);
                if (scene.isLoaded) yield return scene;
            }
        }

        private static void CollectInHierarchy(GameObject root, string name, List<GameObject> result)
        {
            if (root.name == name) result.Add(root);
            foreach (Transform child in root.transform)
                CollectInHierarchy(child.gameObject, name, result);
        }
    }
}
#endif
