using Tsvrc.Core;
using UdonSharp;
using UnityEngine;

namespace Tsvrc.Editor.V2
{
    // Single scene-based config for everything PoolModule/SingletonModule/(future)Construct-
    // /FactoryModule need. Singletons/Constructs are scene-object references, which only a
    // scene object can hold (a ScriptableObject asset cannot reference a scene object - a scene
    // object only has a fileID meaningful within its own scene file, no stable cross-file
    // address). PooledObjects/Factories are asset/prefab references, which a scene object can
    // also hold fine - only the reverse (asset -> scene) is impossible. So everything lives here
    // together rather than being split across an asset and a scene component.
    //
    // Auto-created/self-healed as a child of TsvrcGenerated by ScaffoldModule, and always
    // tagged EditorOnly so it's stripped from the VRChat build - it's compile-time-only
    // configuration, never part of the generated runtime hierarchy. Plain MonoBehaviour, not
    // UdonSharpBehaviour: it's never compiled to Udon, only read by editor tooling.
    //
    // Deliberately NOT under an Editor/ folder and NOT wrapped in #if UNITY_EDITOR: scripts
    // under a folder named "Editor" are excluded from the runtime assembly entirely, and
    // GameObject.AddComponent silently fails for them - the component can be created here but
    // never actually attaches to a scene object. The EditorOnly tag on its GameObject (set by
    // ScaffoldModule) is what strips it from the VRChat build, not the script's location.
    public class TsvrcConfig : MonoBehaviour
    {
        [Tooltip("Scene objects exposed as named fields on _ts.Singleton. Drag a GameObject or Component here.")]
        public Object[] Singletons;
        [Tooltip("UdonSharpBehaviour prefabs to pool. Must be prefab assets, not scene objects.")]
        public UdonSharpBehaviour[] PooledObjects;
        [Tooltip("TsvrcBehaviours that are always active in the scene, not pooled. Constructed at startup.")]
        public TsvrcBehaviour[] Constructs;
        [Tooltip("Factory groups for runtime-instantiated (non-networked) prefabs.")]
        public TsvrcFactoryGroup[] Factories;
    }
}
