#if UNITY_EDITOR
using System.Collections.Generic;
using System.Linq;
using Tsvrc.Config;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

namespace Tsvrc.Editor
{
    // Open via Tsvrc > Configure.
    // Tabs come from TsGenerator.CreateModules(), filtered to modules with a non-null TabLabel.
    internal class TsWindow : EditorWindow
    {
        private List<TsModule> _tabs;
        private string[] _tabLabels;

        private int _tabIndex;
        private Vector2 _scroll;
        private TsConfig _config;
        private SerializedObject _so;

        [MenuItem("Tsvrc/Configure", priority = 1)]
        private static void Open()
        {
            var window = GetWindow<TsWindow>("Configure");
            window.minSize = new Vector2(420, 360);
            window.Show();
        }

        private void OnEnable()
        {
            TsGenerator.StateChanged += HandleStateChanged;
            ReloadTabs();
            ReloadConfig();
        }

        private void OnDisable() => TsGenerator.StateChanged -= HandleStateChanged;

        private void HandleStateChanged()
        {
            ReloadConfig();
            Repaint();
        }

        private void OnFocus()
        {
            if (_config == null)
                ReloadConfig();
        }

        // Built once, never rebuilt on StateChanged: module instances are stateless re TsConfig
        // (DrawTab reads the SerializedObject fresh), but may hold tab-only UI state (e.g.
        // FactoryModule's per-group foldouts). Rebuilding on every regenerate would silently reset
        // that state, so ReloadConfig() below - not this method - runs on every TsGenerator.StateChanged.
        private void ReloadTabs()
        {
            _tabs = TsGenerator.CreateModules().Where(m => m.TabLabel != null).ToList();
            _tabLabels = _tabs.Select(m => m.TabLabel).ToArray();
            if (_tabIndex >= _tabs.Count) _tabIndex = 0;
        }

        private void ReloadConfig()
        {
            // TsConfig is a scene component (it needs to be able to hold scene-object
            // references), auto-created/healed under TsGenerated by ScaffoldModule - found,
            // not loaded as an asset. Scoped to the linked scene once one is set - see
            // TsLinkedScene's own doc comment for why "whatever scene is open" isn't safe.
            _config = TsLinkedScene.Find<TsConfig>();
            _so = _config != null ? new SerializedObject(_config) : null;
        }

        private void OnGUI()
        {
            DrawLinkedScene();
            DrawStatus();
            DrawBuiltinConfigWarning();
            DrawCollisionWarning();
            DrawRunWarnings();
            DrawTreeShakingSummary();

            if (_config == null)
            {
                DrawActionFooter();
                return;
            }

            DrawTreeShakingControls();

            if (_tabs.Count == 0)
            {
                EditorGUILayout.HelpBox("No configurable modules found.", MessageType.Info);
                return;
            }

            int newIndex = GUILayout.Toolbar(_tabIndex, _tabLabels);
            if (newIndex != _tabIndex) { _tabIndex = newIndex; _scroll = Vector2.zero; }

            EditorGUILayout.LabelField(_tabs[_tabIndex].TabDescription, EditorStyles.wordWrappedMiniLabel);
            EditorGUILayout.Space(4);

            _so.Update();
            _scroll = EditorGUILayout.BeginScrollView(_scroll);
            _tabs[_tabIndex].DrawTab(_so);
            EditorGUILayout.EndScrollView();
            _so.ApplyModifiedProperties();

            EditorGUILayout.Space(8);
            EditorGUILayout.LabelField(string.Empty, GUI.skin.horizontalSlider);
            DrawActionFooter();
        }

        // The one scene TsGenerator is allowed to read scene config from - see TsLinkedScene's
        // own doc comment for why "whatever scene is open" isn't safe. Drawn first since every
        // other status/warning below depends on whether the linked scene (if any) is loaded.
        private void DrawLinkedScene()
        {
            string currentPath = TsLinkedScene.ScenePath;
            var currentAsset = string.IsNullOrEmpty(currentPath) ? null : AssetDatabase.LoadAssetAtPath<SceneAsset>(currentPath);

            EditorGUILayout.BeginHorizontal();
            EditorGUILayout.PrefixLabel("Linked Scene");
            var newAsset = (SceneAsset)EditorGUILayout.ObjectField(currentAsset, typeof(SceneAsset), false);
            EditorGUILayout.EndHorizontal();

            if (newAsset != currentAsset)
            {
                TsLinkedScene.ScenePath = newAsset != null ? AssetDatabase.GetAssetPath(newAsset) : null;
                ReloadConfig();
            }

            var message = DetermineLinkedSceneWarning(currentPath, TsLinkedScene.IsConfiguredButNotLoaded, TsLinkedScene.IsConfiguredButMissing);
            if (message == null)
                message = DetermineMissingLinkWarning(TsLinkedScene.IsConfigured, ScaffoldModule.ScaffoldFileExists());
            if (message != null)
                TsEditorGUI.DrawStatusBox(message, MessageType.Warning);

            EditorGUILayout.Space(4);
        }

        // Pure so it's directly unit-testable without driving OnGUI/EditorWindow. Returns null
        // when there's nothing to warn about (no scene linked yet, or the linked one is loaded).
        // isConfiguredButMissing (the scene asset was deleted, not just renamed/moved) gets its
        // own message, since "open it" isn't a real recovery action once the asset is gone.
        internal static string DetermineLinkedSceneWarning(string linkedScenePath, bool isConfiguredButNotLoaded, bool isConfiguredButMissing)
        {
            if (isConfiguredButMissing)
                return "The previously linked scene no longer exists on disk. Pick a new one above.";
            if (!isConfiguredButNotLoaded) return null;
            return $"'{linkedScenePath}' is linked but not currently open. Tsvrc will not read or write " +
                "anything until it's open, so it's never affected by any other scene - including a test run's.";
        }

        // If TsLinkedSceneConfig.asset itself was deleted (or never survived a fresh clone), every
        // module silently reverts to legacy unscoped behavior with no other symptom. Real
        // generated content already existing on disk despite nothing being linked is the one
        // detectable trace that a link used to exist and was lost. Only shown when
        // DetermineLinkedSceneWarning above has nothing to say; the two are mutually exclusive.
        internal static string DetermineMissingLinkWarning(bool isConfigured, bool generatedScaffoldFileExists)
        {
            if (isConfigured || !generatedScaffoldFileExists) return null;
            return "Generated content already exists in the generated folder, but no scene is linked to it - " +
                "was TsLinkedSceneConfig.asset deleted? Re-select the correct scene above to restore it.";
        }

        private void DrawStatus()
        {
            bool pending = TsGenerator.IsBootstrapPending;
            bool playMode = EditorApplication.isPlayingOrWillChangePlaymode;
            var (message, type) = DetermineStatus(_config != null, pending, playMode, TsLinkedScene.IsConfiguredButNotLoaded, TsLinkedScene.IsConfigured);
            if (message != null)
                TsEditorGUI.DrawStatusBox(message, type);
        }

        // A missing TsBuiltinConfig.asset (package-shipped, so a bad submodule update or merge
        // can lose it for the whole team at once) silently drops every library-provided
        // Singleton/pool prefab/Factory group with no other symptom.
        private void DrawBuiltinConfigWarning()
        {
            var message = DetermineBuiltinConfigWarning(TsModule.IsBuiltinConfigMissing());
            if (message != null)
                TsEditorGUI.DrawStatusBox(message, MessageType.Warning);
        }

        // Pure so it's directly unit-testable without driving OnGUI/EditorWindow.
        internal static string DetermineBuiltinConfigWarning(bool isBuiltinConfigMissing)
        {
            if (!isBuiltinConfigMissing) return null;
            return $"Tsvrc's builtin config asset is missing at '{TsModule.BuiltinConfigPath}' - library-provided " +
                "singletons, pool prefabs, and factories will not be included until it's restored.";
        }

        private void DrawCollisionWarning()
        {
            var message = DetermineCollisionWarning(TsGenerator.LastFieldNameCollisions);
            if (message != null)
                TsEditorGUI.DrawStatusBox(message, MessageType.Warning);
        }

        // Pure so it's directly unit-testable without driving OnGUI/EditorWindow. Returns null
        // when there's nothing to warn about (the common case).
        internal static string DetermineCollisionWarning(IReadOnlyList<string> collisions)
        {
            if (collisions == null || collisions.Count == 0) return null;
            return $"{collisions.Count} field name(s) dropped from the last regenerate due to a naming " +
                $"conflict between modules: {string.Join(", ", collisions)}. Use __Alias__ on the " +
                "GameObject name(s) to assign a unique name, then regenerate.";
        }

        private void DrawRunWarnings()
        {
            var message = DetermineRunWarningsSummary(TsGenerator.LastRunWarnings);
            if (message != null)
                TsEditorGUI.DrawStatusBox(message, MessageType.Warning);
        }

        // Pure so it's directly unit-testable without driving OnGUI/EditorWindow. Returns null when
        // there's nothing to report. Complements DetermineCollisionWarning, which gives that one
        // common case its own actionable message; this one only ever shows a short summary.
        internal static string DetermineRunWarningsSummary(IReadOnlyList<string> warnings, int maxShown = 3)
        {
            if (warnings == null || warnings.Count == 0) return null;

            var shown = warnings.Take(maxShown).ToList();
            string list = string.Join("\n", shown.Select(w => $"• {w}"));
            string more = warnings.Count > shown.Count ? $"\n(+{warnings.Count - shown.Count} more — see Console)" : "";
            return $"{warnings.Count} issue(s) reported during the last regenerate:\n{list}{more}";
        }

        // Surfaces the most recent Run() pass's tree-shaking exclusions and grace-period
        // inclusions so a developer sees what disappeared (or is about to) without digging through
        // the Console. Both Info, not Warning: this is the feature working as intended. Drawn as
        // two separate boxes since they call for different reactions: "gone, bring it back if you
        // want it" versus "still here for now, but reference it soon."
        private void DrawTreeShakingSummary()
        {
            var graceMessage = DetermineTreeShakingGraceSummary(TsGenerator.LastTreeShakingGraceIncluded);
            if (graceMessage != null)
                TsEditorGUI.DrawStatusBox(graceMessage, MessageType.Info);

            var exclusionMessage = DetermineTreeShakingSummary(TsGenerator.LastTreeShakingExclusions);
            if (exclusionMessage != null)
                TsEditorGUI.DrawStatusBox(exclusionMessage, MessageType.Info);
        }

        // Pure so it's directly unit-testable without driving OnGUI/EditorWindow. Returns null
        // when there's nothing to report (tree-shaking off, or on with nothing excluded).
        internal static string DetermineTreeShakingSummary(IReadOnlyList<string> exclusions, int maxShown = 5)
        {
            if (exclusions == null || exclusions.Count == 0) return null;

            var shown = exclusions.Take(maxShown).ToList();
            string list = string.Join(", ", shown);
            string more = exclusions.Count > shown.Count ? $" (+{exclusions.Count - shown.Count} more)" : "";
            string plural = exclusions.Count == 1 ? "entry" : "entries";
            return $"Tree-shaking excluded {exclusions.Count} unused {plural} this pass: {list}{more}. " +
                "Add a name to Force Include Names below to keep generating it, or reference it from a TsvrcBehaviour.";
        }

        // Pure so it's directly unit-testable without driving OnGUI/EditorWindow. Returns null
        // when there's nothing to report. Worded as reassurance, not a warning: this is the
        // normal, expected state for anything just registered or just stopped being referenced.
        internal static string DetermineTreeShakingGraceSummary(IReadOnlyList<string> graceIncluded, int maxShown = 5)
        {
            if (graceIncluded == null || graceIncluded.Count == 0) return null;

            var shown = graceIncluded.Take(maxShown).ToList();
            string list = string.Join(", ", shown);
            string more = graceIncluded.Count > shown.Count ? $" (+{graceIncluded.Count - shown.Count} more)" : "";
            string plural = graceIncluded.Count == 1 ? "entry isn't" : "entries aren't";
            string pronoun = graceIncluded.Count == 1 ? "it" : "them";
            return $"{graceIncluded.Count} {plural} referenced anywhere in the project yet, kept for now: " +
                $"{list}{more}. This is normal right after registering something new - reference {pronoun} soon " +
                $"(or add {pronoun} to Force Include Names below), or {pronoun} may be excluded on a future regenerate.";
        }

        // Drawn only once a TsConfig exists (mirrors every tab below it): TreeShakeUnused and
        // ForceIncludeNames both live on TsConfig, one toggle per linked scene/project rather
        // than per module, so there's nothing to bind to before that.
        private void DrawTreeShakingControls()
        {
            if (_so == null) return;

            _so.Update();
            var treeShakeProp = _so.FindProperty("TreeShakeUnused");
            EditorGUILayout.PropertyField(treeShakeProp, new GUIContent("Tree-Shake Unused Singletons/Factories (Experimental)"));
            if (treeShakeProp.boolValue)
            {
                EditorGUILayout.PropertyField(_so.FindProperty("ForceIncludeNames"), new GUIContent("Force Include Names"), true);
                TsEditorGUI.DrawStatusBox(
                    "Singleton and Factory entries not referenced anywhere in the project (via _ts.Name or " +
                    "CreateName(...)) will be excluded on the next regenerate. List a name above to always keep it.",
                    MessageType.Info);
            }
            _so.ApplyModifiedProperties();
            EditorGUILayout.Space(4);
        }

        // Pure so it's directly unit-testable without driving OnGUI/EditorWindow.
        // isConfiguredButNotLoaded/isLinked default to "no linked-scene complication at all,
        // just report on hasConfig", so callers that don't care about scene-linking state can
        // omit them.
        internal static (string message, MessageType type) DetermineStatus(
            bool hasConfig, bool isBootstrapPending, bool isPlayMode,
            bool isConfiguredButNotLoaded = false, bool isLinked = true)
        {
            // Checked first: TsGenerator.Run() itself bails out during play mode (see its own
            // isPlayingOrWillChangePlaymode guard), so nothing below would be accurate anyway.
            if (isPlayMode)
                return ("Exit Play Mode to configure or regenerate Tsvrc.", MessageType.Warning);
            if (isBootstrapPending)
                return ("Setting up Tsvrc… waiting for scripts to compile.", MessageType.Info);
            // DrawLinkedScene's own warning box, drawn directly above this one, already explains
            // this state in full ("linked but not open" / "no longer exists"). A second, "not yet
            // set up" box here would contradict it: one implies first-time setup, the other
            // implies the link already exists.
            if (isConfiguredButNotLoaded)
                return (null, MessageType.None);
            if (!hasConfig)
                return ("Tsvrc is not yet set up in this scene. Click below to get started.", MessageType.Info);
            // hasConfig here came from the legacy "search whatever scene is open" fallback, used
            // when nothing is linked yet: a real, working setup that simply never got linked,
            // leaving the whole corruption-safety net this feature exists for turned off with no
            // other indication.
            if (!isLinked)
                return ("Tsvrc is set up here, but no scene is linked yet. Pick this scene above to enable safe, scene-scoped regeneration.", MessageType.Warning);
            return ("Tsvrc is set up.", MessageType.None);
        }

        // "Initialize Tsvrc" and "Force Regenerate" run the exact same action
        // (TsGenerator.ManualGenerate()) - only the label changes, since a first-time setup and a
        // maintenance regenerate are very different mental models for the person clicking it.
        // While the linked scene isn't open, regenerating is impossible, so this offers to open
        // it instead of a "Force Regenerate" that would silently do nothing. isConfiguredButMissing
        // takes priority over that: once the asset itself is gone, "open it" isn't a real recovery
        // action either, so the button is disabled instead (see IsActionEnabled) and the label
        // just names the blocker.
        internal static string DetermineActionLabel(bool hasConfig, bool isConfiguredButNotLoaded, bool isConfiguredButMissing = false)
        {
            if (isConfiguredButMissing) return "Linked Scene Missing";
            if (isConfiguredButNotLoaded) return "Open Linked Scene";
            return hasConfig ? "Force Regenerate" : "Initialize Tsvrc";
        }

        // Disabled while a bootstrap triggered by an earlier click is still waiting on a recompile,
        // during play mode (TsGenerator.Run() itself is a no-op there - see ValidateManualGenerate
        // on the equivalent menu item), or once the linked scene asset no longer exists at all:
        // "Open Linked Scene" would just fail, so there is no action left to offer until a new
        // scene is picked via the field above.
        internal static bool IsActionEnabled(bool isBootstrapPending, bool isPlayMode, bool isConfiguredButMissing = false) =>
            !isBootstrapPending && !isPlayMode && !isConfiguredButMissing;

        // Explains *why* the button above is disabled, shown as its tooltip. Null when enabled.
        internal static string DetermineActionDisabledReason(bool isBootstrapPending, bool isPlayMode, bool isConfiguredButMissing = false)
        {
            if (isPlayMode) return "Exit Play Mode before regenerating.";
            if (isBootstrapPending) return "Waiting for the current setup pass to finish compiling.";
            if (isConfiguredButMissing) return "The linked scene no longer exists - pick a new one above.";
            return null;
        }

        private void DrawActionFooter()
        {
            bool pending = TsGenerator.IsBootstrapPending;
            bool playMode = EditorApplication.isPlayingOrWillChangePlaymode;
            bool missing = TsLinkedScene.IsConfiguredButMissing;
            bool notLoaded = TsLinkedScene.IsConfiguredButNotLoaded;
            string label = DetermineActionLabel(_config != null, notLoaded, missing);
            bool enabled = IsActionEnabled(pending, playMode, missing);
            string disabledReason = DetermineActionDisabledReason(pending, playMode, missing);

            if (TsEditorGUI.PrimaryButton(label, enabled, disabledReason))
            {
                if (notLoaded) OpenLinkedScene();
                else TsGenerator.ManualGenerate();
                GUIUtility.ExitGUI();
            }
        }

        private static void OpenLinkedScene()
        {
            if (EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
                EditorSceneManager.OpenScene(TsLinkedScene.ScenePath, OpenSceneMode.Single);
        }
    }
}
#endif
