#if UNITY_EDITOR
using System.Collections.Generic;
using System.Linq;
using Tsvrc.Config;
using UnityEditor;
using UnityEngine;

namespace Tsvrc.Editor
{
    // Open via Tsvrc > Configure.
    // Tabs come from TsGenerator.CreateModules(), filtered to modules with a non-null TabLabel.
    internal class TsWindow : EditorWindow
    {
        private List<TsModule> _tabs;
        private string[] _tabLabels;

        private int _tabIndex;
        private Vector2 _scroll;
        private TsConfig _config;
        private SerializedObject _so;

        [MenuItem("Tsvrc/Configure", priority = 1)]
        private static void Open()
        {
            var window = GetWindow<TsWindow>("Configure");
            window.minSize = new Vector2(420, 360);
            window.Show();
        }

        private void OnEnable()
        {
            TsGenerator.StateChanged += HandleStateChanged;
            ReloadTabs();
            ReloadConfig();
        }

        private void OnDisable() => TsGenerator.StateChanged -= HandleStateChanged;

        private void HandleStateChanged()
        {
            ReloadConfig();
            Repaint();
        }

        private void OnFocus()
        {
            if (_config == null)
                ReloadConfig();
        }

        // Built once, never rebuilt on StateChanged: module instances are stateless re TsConfig
        // (DrawTab reads the SerializedObject fresh), but may hold tab-only UI state (e.g.
        // FactoryModule's per-group foldouts). Rebuilding on every regenerate would silently reset
        // that state, so ReloadConfig() below - not this method - runs on every TsGenerator.StateChanged.
        private void ReloadTabs()
        {
            _tabs = TsGenerator.CreateModules().Where(m => m.TabLabel != null).ToList();
            _tabLabels = _tabs.Select(m => m.TabLabel).ToArray();
            if (_tabIndex >= _tabs.Count) _tabIndex = 0;
        }

        private void ReloadConfig()
        {
            // TsConfig is a scene component (it needs to be able to hold scene-object
            // references), auto-created/healed under TsGenerated by ScaffoldModule - found,
            // not loaded as an asset.
            _config = UnityEngine.Object.FindObjectOfType<TsConfig>(true);
            _so = _config != null ? new SerializedObject(_config) : null;
        }

        private void OnGUI()
        {
            DrawStatus();
            DrawCollisionWarning();
            DrawRunWarnings();

            if (_config == null)
            {
                DrawActionFooter();
                return;
            }

            if (_tabs.Count == 0)
            {
                EditorGUILayout.HelpBox("No configurable modules found.", MessageType.Info);
                return;
            }

            int newIndex = GUILayout.Toolbar(_tabIndex, _tabLabels);
            if (newIndex != _tabIndex) { _tabIndex = newIndex; _scroll = Vector2.zero; }

            EditorGUILayout.LabelField(_tabs[_tabIndex].TabDescription, EditorStyles.wordWrappedMiniLabel);
            EditorGUILayout.Space(4);

            _so.Update();
            _scroll = EditorGUILayout.BeginScrollView(_scroll);
            _tabs[_tabIndex].DrawTab(_so);
            EditorGUILayout.EndScrollView();
            _so.ApplyModifiedProperties();

            EditorGUILayout.Space(8);
            EditorGUILayout.LabelField(string.Empty, GUI.skin.horizontalSlider);
            DrawActionFooter();
        }

        private void DrawStatus()
        {
            bool pending = TsGenerator.IsBootstrapPending;
            bool playMode = EditorApplication.isPlayingOrWillChangePlaymode;
            var (message, type) = DetermineStatus(_config != null, pending, playMode);
            TsEditorGUI.DrawStatusBox(message, type);
        }

        private void DrawCollisionWarning()
        {
            var message = DetermineCollisionWarning(TsGenerator.LastFieldNameCollisions);
            if (message != null)
                TsEditorGUI.DrawStatusBox(message, MessageType.Warning);
        }

        // Pure so it's directly unit-testable without driving OnGUI/EditorWindow. Returns null
        // when there's nothing to warn about (the common case).
        internal static string DetermineCollisionWarning(IReadOnlyList<string> collisions)
        {
            if (collisions == null || collisions.Count == 0) return null;
            return $"{collisions.Count} field name(s) dropped from the last regenerate due to a naming " +
                $"conflict between modules: {string.Join(", ", collisions)}. Use __Alias__ on the " +
                "GameObject name(s) to assign a unique name, then regenerate.";
        }

        private void DrawRunWarnings()
        {
            var message = DetermineRunWarningsSummary(TsGenerator.LastRunWarnings);
            if (message != null)
                TsEditorGUI.DrawStatusBox(message, MessageType.Warning);
        }

        // Pure so it's directly unit-testable without driving OnGUI/EditorWindow. Returns null when
        // there's nothing to report. Complements DetermineCollisionWarning, which gives that one
        // common case its own actionable message; this one only ever shows a short summary.
        internal static string DetermineRunWarningsSummary(IReadOnlyList<string> warnings, int maxShown = 3)
        {
            if (warnings == null || warnings.Count == 0) return null;

            var shown = warnings.Take(maxShown).ToList();
            string list = string.Join("\n", shown.Select(w => $"• {w}"));
            string more = warnings.Count > shown.Count ? $"\n(+{warnings.Count - shown.Count} more — see Console)" : "";
            return $"{warnings.Count} issue(s) reported during the last regenerate:\n{list}{more}";
        }

        // Pure so it's directly unit-testable without driving OnGUI/EditorWindow.
        internal static (string message, MessageType type) DetermineStatus(bool hasConfig, bool isBootstrapPending, bool isPlayMode)
        {
            // Checked first: TsGenerator.Run() itself bails out during play mode (see its own
            // isPlayingOrWillChangePlaymode guard), so nothing below would be accurate anyway.
            if (isPlayMode)
                return ("Exit Play Mode to configure or regenerate Tsvrc.", MessageType.Warning);
            if (isBootstrapPending)
                return ("Setting up Tsvrc… waiting for scripts to compile.", MessageType.Info);
            if (!hasConfig)
                return ("Tsvrc is not yet set up in this scene. Click below to get started.", MessageType.Info);
            return ("Tsvrc is set up.", MessageType.None);
        }

        // "Initialize Tsvrc" and "Force Regenerate" run the exact same action
        // (TsGenerator.ManualGenerate()) - only the label changes, since a first-time setup and a
        // maintenance regenerate are very different mental models for the person clicking it.
        internal static string DetermineActionLabel(bool hasConfig) => hasConfig ? "Force Regenerate" : "Initialize Tsvrc";

        // Disabled while a bootstrap triggered by an earlier click is still waiting on a recompile,
        // or during play mode (TsGenerator.Run() itself is a no-op there - see ValidateManualGenerate
        // on the equivalent menu item).
        internal static bool IsActionEnabled(bool isBootstrapPending, bool isPlayMode) => !isBootstrapPending && !isPlayMode;

        // Explains *why* the button above is disabled, shown as its tooltip. Null when enabled.
        internal static string DetermineActionDisabledReason(bool isBootstrapPending, bool isPlayMode)
        {
            if (isPlayMode) return "Exit Play Mode before regenerating.";
            if (isBootstrapPending) return "Waiting for the current setup pass to finish compiling.";
            return null;
        }

        private void DrawActionFooter()
        {
            bool pending = TsGenerator.IsBootstrapPending;
            bool playMode = EditorApplication.isPlayingOrWillChangePlaymode;
            string label = DetermineActionLabel(_config != null);
            bool enabled = IsActionEnabled(pending, playMode);
            string disabledReason = DetermineActionDisabledReason(pending, playMode);

            if (TsEditorGUI.PrimaryButton(label, enabled, disabledReason))
            {
                TsGenerator.ManualGenerate();
                GUIUtility.ExitGUI();
            }
        }
    }
}
#endif
