#if UNITY_EDITOR
using System.Collections.Generic;
using System.Linq;
using Tsvrc.Config;
using UnityEditor;
using UnityEngine;

namespace Tsvrc.Editor
{
    // Open via Tsvrc > Configure.
    // Tabs come from TsGenerator.CreateModules(), filtered to modules with a non-null TabLabel.
    internal class TsWindow : EditorWindow
    {
        private List<TsModule> _tabs;
        private string[] _tabLabels;

        private int _tabIndex;
        private Vector2 _scroll;
        private TsConfig _config;
        private SerializedObject _so;

        [MenuItem("Tsvrc/Configure")]
        private static void Open() => GetWindow<TsWindow>("Tsvrc Configure").Show();

        private void OnEnable() => Reload();

        private void OnFocus()
        {
            if (_config == null)
                Reload();
        }

        private void Reload()
        {
            _tabs = TsGenerator.CreateModules().Where(m => m.TabLabel != null).ToList();
            _tabLabels = _tabs.Select(m => m.TabLabel).ToArray();
            if (_tabIndex >= _tabs.Count) _tabIndex = 0;

            // TsConfig is a scene component (it needs to be able to hold scene-object
            // references), auto-created/healed under TsGenerated by ScaffoldModule - found,
            // not loaded as an asset.
            _config = UnityEngine.Object.FindObjectOfType<TsConfig>(true);
            _so = _config != null ? new SerializedObject(_config) : null;
        }

        private void OnGUI()
        {
            EditorGUILayout.LabelField("Tsvrc Configure", EditorStyles.boldLabel);
            EditorGUILayout.Space(2);

            if (_config == null)
            {
                DrawNoConfig();
                return;
            }

            if (_tabs.Count == 0)
            {
                EditorGUILayout.HelpBox("No configurable modules found.", MessageType.Info);
                return;
            }

            int newIndex = GUILayout.Toolbar(_tabIndex, _tabLabels);
            if (newIndex != _tabIndex) { _tabIndex = newIndex; _scroll = Vector2.zero; }

            EditorGUILayout.LabelField(_tabs[_tabIndex].TabDescription, EditorStyles.wordWrappedMiniLabel);
            EditorGUILayout.Space(4);

            _so.Update();
            _scroll = EditorGUILayout.BeginScrollView(_scroll);
            _tabs[_tabIndex].DrawTab(_so);
            EditorGUILayout.EndScrollView();
            _so.ApplyModifiedProperties();

            EditorGUILayout.Space(8);
            EditorGUILayout.LabelField(string.Empty, GUI.skin.horizontalSlider);
            if (GUILayout.Button("Force Regenerate"))
            {
                TsGenerator.ManualGenerate();
                GUIUtility.ExitGUI();
            }
        }

        private void DrawNoConfig()
        {
            EditorGUILayout.HelpBox(
                "No TsConfig found in the scene. It is auto-created under TsGenerated — press Force Regenerate below to create it.",
                MessageType.Info);
            EditorGUILayout.LabelField(string.Empty, GUI.skin.horizontalSlider);
            if (GUILayout.Button("Force Regenerate"))
            {
                TsGenerator.ManualGenerate();
                GUIUtility.ExitGUI();
            }
        }
    }
}
#endif
