using System;
using NUnit.Framework;
using Tsvrc.Editor;

namespace Tsvrc.Tests.Editor
{
    // Tests feed FactoryModule.GenerateCode() synthetic entries via reflection, covering the
    // three Create{Name}(Transform parent) code-shape branches.
    public class FactoryModuleGenerateCodeTests
    {
        private static readonly Type EntryType = CodeGenModuleReflection.NestedType(typeof(FactoryModule), "FactoryEntry");

        private static FactoryModule BuildModule(params object[] entries)
        {
            var module = new FactoryModule();
            PrivateFieldAccess.SetField(module, "_entries", CodeGenModuleReflection.BuildList(EntryType, entries));
            return module;
        }

        private static object Entry(string name, string typeName, string ns, bool isTsvrcBehaviour)
            => CodeGenModuleReflection.BuildEntry(EntryType,
                ("Name", name), ("TypeName", typeName), ("TypeNamespace", ns),
                ("IsTsvrcBehaviour", isTsvrcBehaviour), ("PrefabAsset", null));

        [Test]
        public void GenerateCode_EmptyEntries_ReturnsStubWithNoMethods()
        {
            string expected =
$@"// <auto-generated/>
// Generated by TsvrcGenerator. Do not edit, changes will be overwritten.
// Regenerated automatically on domain reload, or manually via Tsvrc > Force Regenerate.

using UdonSharp;
using UnityEngine;

namespace {ScaffoldModule.CompiledNamespace}
{{
    public partial class {ScaffoldModule.CompiledClassName}
    {{
    }}
}}
";

            GeneratedCodeAssert.AreEqual(expected, BuildModule().GenerateCode());
        }

        [Test]
        public void GenerateCode_BareGameObjectEntry_ReturnsGoDirectly()
        {
            var module = BuildModule(Entry("Bullet", "GameObject", "", isTsvrcBehaviour: false));

            string code = module.GenerateCode();

            StringAssert.Contains("private GameObject _factoryBullet;", code);
            StringAssert.Contains("public GameObject CreateBullet(Transform parent)", code);
            StringAssert.Contains("return go;", code);
            StringAssert.DoesNotContain("GetComponent<GameObject>", code);
        }

        [Test]
        public void GenerateCode_TsvrcBehaviourEntry_GetsComponentAndConditionallyConstructs()
        {
            var module = BuildModule(Entry("Manager", "StateManager", "Tsvrc.StateMachine", isTsvrcBehaviour: true));

            string code = module.GenerateCode();

            StringAssert.Contains("public StateManager CreateManager(Transform parent)", code);
            StringAssert.Contains("var instance = go.GetComponent<StateManager>();", code);
            StringAssert.Contains("if (instance != null) instance.TsConstruct(this);", code);
            StringAssert.Contains("return instance;", code);
        }

        [Test]
        public void GenerateCode_OtherComponentEntry_GetsComponentAndReturnsDirectlyNoConstruct()
        {
            var module = BuildModule(Entry("Body", "Rigidbody", "UnityEngine", isTsvrcBehaviour: false));

            string code = module.GenerateCode();

            StringAssert.Contains("public Rigidbody CreateBody(Transform parent)", code);
            StringAssert.Contains("return go.GetComponent<Rigidbody>();", code);
            StringAssert.DoesNotContain("TsConstruct", code);
        }

        [Test]
        public void GenerateCode_EveryEntry_DeclaresItsFactoryFieldRegardlessOfBranch()
        {
            var module = BuildModule(
                Entry("A", "GameObject", "", false),
                Entry("B", "StateManager", "Tsvrc.StateMachine", true),
                Entry("C", "Rigidbody", "UnityEngine", false));

            string code = module.GenerateCode();

            StringAssert.Contains("private GameObject _factoryA;", code);
            StringAssert.Contains("private GameObject _factoryB;", code);
            StringAssert.Contains("private GameObject _factoryC;", code);
        }
    }
}
