using NUnit.Framework;
using Tsvrc.Editor;

namespace Tsvrc.Tests.Editor
{
    // MemoryModule.GenerateCode() has no config-driven variation at all (LoadConfig() is
    // a no-op). CODEGEN_TESTING_PLAN.md Phase G2.7.
    public class MemoryModuleGenerateCodeTests
    {
        [Test]
        public void GenerateCode_IsAFixedTemplate()
        {
            string expected =
$@"// <auto-generated/>
// Generated by TsvrcGenerator. Do not edit, changes will be overwritten.
// Regenerated automatically on domain reload, or manually via Tsvrc > Force Regenerate.

using Tsvrc.Utils;
using UdonSharp;
using UnityEngine;

namespace {ScaffoldModule.CompiledNamespace}
{{
    public partial class {ScaffoldModule.CompiledClassName}
    {{
        [ReadOnly] [SerializeField] private TsMemory _memory;

        public override TsMemory Memory => _memory;

        public void _TsMemoryStart()
        {{
            _memory.TsConstruct(this);
        }}
    }}
}}
";

            GeneratedCodeAssert.AreEqual(expected, new MemoryModule().GenerateCode());
        }
    }
}
