using NUnit.Framework;
using Tsvrc.Editor;

namespace Tsvrc.Tests.Editor
{
    // ScaffoldModule.GenerateCode() is the one truly parameter-free golden file in the
    // whole generator - it never varies with config. CODEGEN_TESTING_PLAN.md Phase G2.1.
    public class ScaffoldModuleGenerateCodeTests
    {
        [Test]
        public void GenerateCode_IsAFixedTemplate_WithStartCallOrderMemoryThenSingletonThenPoolThenConstructThenInstance()
        {
            string expected =
$@"// <auto-generated/>
// Generated by TsvrcGenerator. Do not edit, changes will be overwritten.
// Regenerated automatically on domain reload, or manually via Tsvrc > Force Regenerate.
using UdonSharp;
using UnityEngine;

namespace {ScaffoldModule.CompiledNamespace}
{{
    [UdonBehaviourSyncMode(BehaviourSyncMode.None)]
    [AddComponentMenu("""")]
    public partial class {ScaffoldModule.CompiledClassName} : TsvrcRoot
    {{
        void Start()
        {{
            _TsMemoryStart();
            _TsSingletonStart();
            _TsPoolStart();
            _TsConstructStart();
            _TsInstanceStart();
        }}
    }}
}}";

            Assert.AreEqual(expected, new ScaffoldModule().GenerateCode());
        }

        [Test]
        public void GenerateCode_CalledTwice_IsByteForByteIdentical()
        {
            // Determinism is what makes TsvrcGenerator.WriteIfChanged's content-diff meaningful.
            var module = new ScaffoldModule();

            Assert.AreEqual(module.GenerateCode(), module.GenerateCode());
        }
    }
}
