using System;
using NUnit.Framework;
using Tsvrc.Editor;

namespace Tsvrc.Tests.Editor
{
    // Tests feed SingletonModule.GenerateCode() synthetic entries via reflection, bypassing
    // the real LoadConfig()/AssetDatabase-coupled pipeline entirely.
    public class SingletonModuleGenerateCodeTests
    {
        private static readonly Type EntryType = PrivateFieldAccess.NestedType(typeof(SingletonModule), "SingletonEntry");

        private static SingletonModule BuildModule(params object[] entries)
        {
            var module = new SingletonModule();
            PrivateFieldAccess.SetField(module, "_entries", PrivateFieldAccess.BuildList(EntryType, entries));
            return module;
        }

        private static object Entry(string name, string typeName, string ns)
            => PrivateFieldAccess.BuildEntry(EntryType,
                ("Name", name), ("TypeName", typeName), ("Namespace", ns), ("SourceObject", null));

        [Test]
        public void GenerateCode_EmptyEntries_ReturnsStubWithEmptyStartMethod()
        {
            string expected =
$@"// <auto-generated/>
// Generated by TsvrcGenerator. Do not edit, changes will be overwritten.
// Regenerated automatically on domain reload, or manually via Tsvrc > Force Regenerate.

namespace {ScaffoldModule.CompiledNamespace}
{{
    public partial class {ScaffoldModule.CompiledClassName}
    {{
        public void _TsSingletonStart()
        {{
        }}
    }}
}}
";

            GeneratedCodeAssert.AreEqual(expected, BuildModule().GenerateCode());
        }

        [Test]
        public void GenerateCode_NonTsvrcBehaviourEntry_DeclaresFieldButNoConstructCall()
        {
            // Transform is a real, resolvable type but never extends TsvrcBehaviour.
            var module = BuildModule(Entry("Player", "Transform", "UnityEngine"));

            string code = module.GenerateCode();

            StringAssert.Contains("public Transform Player;", code);
            StringAssert.DoesNotContain("Player.TsConstruct(this);", code);
        }

        [Test]
        public void GenerateCode_TsvrcBehaviourEntry_DeclaresFieldAndConstructCall()
        {
            // Tsvrc.StateMachine.StateManager : TsvrcBehaviour - a real production type.
            var module = BuildModule(Entry("Manager", "StateManager", "Tsvrc.StateMachine"));

            string code = module.GenerateCode();

            StringAssert.Contains("public StateManager Manager;", code);
            StringAssert.Contains("Manager.TsConstruct(this);", code);
        }

        [Test]
        public void GenerateCode_MultipleEntries_FieldsAndStartBodyAreAlphabeticalByNameNotConfigOrder()
        {
            var module = BuildModule(
                Entry("Zebra", "StateManager", "Tsvrc.StateMachine"),
                Entry("Alpha", "StateManager", "Tsvrc.StateMachine"),
                Entry("Mid", "StateManager", "Tsvrc.StateMachine"));

            string code = module.GenerateCode();

            int alpha = code.IndexOf("public StateManager Alpha;", StringComparison.Ordinal);
            int mid = code.IndexOf("public StateManager Mid;", StringComparison.Ordinal);
            int zebra = code.IndexOf("public StateManager Zebra;", StringComparison.Ordinal);
            Assert.Greater(mid, alpha, "Fields must be alphabetical, not config order.");
            Assert.Greater(zebra, mid);

            int alphaCall = code.IndexOf("Alpha.TsConstruct(this);", StringComparison.Ordinal);
            int midCall = code.IndexOf("Mid.TsConstruct(this);", StringComparison.Ordinal);
            int zebraCall = code.IndexOf("Zebra.TsConstruct(this);", StringComparison.Ordinal);
            Assert.Greater(midCall, alphaCall, "_TsSingletonStart body must also be alphabetical.");
            Assert.Greater(zebraCall, midCall);
        }

        [Test]
        public void GenerateCode_MultipleNamespaces_UsingsAreDedupedAndIncluded()
        {
            var module = BuildModule(
                Entry("A", "StateManager", "Tsvrc.StateMachine"),
                Entry("B", "StateManager", "Tsvrc.StateMachine"), // duplicate namespace
                Entry("C", "TsMemory", "Tsvrc.Utils"));

            string code = module.GenerateCode();

            int occurrences = 0;
            int index = 0;
            while ((index = code.IndexOf("using Tsvrc.StateMachine;", index, StringComparison.Ordinal)) >= 0)
            {
                occurrences++;
                index++;
            }
            Assert.AreEqual(1, occurrences, "Duplicate namespaces across entries must appear only once in usings.");
            StringAssert.Contains("using Tsvrc.Utils;", code);
            StringAssert.Contains("using UnityEngine;", code);
        }
    }
}
