using System;
using System.Collections.Generic;
using NUnit.Framework;
using Tsvrc.Editor;

namespace Tsvrc.Tests.Editor
{
    // TranslationModule.GenerateCode(), fed a synthetic _languages list via reflection.
    // Phase G2.8.
    public class TranslationModuleGenerateCodeTests
    {
        private static readonly Type EntryType = PrivateFieldAccess.NestedType(typeof(TranslationModule), "LanguageEntry");

        private static object Language(string key, string label, params (string k, string v)[] entries)
        {
            var dict = new Dictionary<string, string>(StringComparer.Ordinal);
            foreach (var (k, v) in entries) dict[k] = v;
            return PrivateFieldAccess.BuildEntry(EntryType, ("Key", key), ("Label", label), ("Entries", dict));
        }

        private static TranslationModule BuildModule(params object[] languages)
        {
            var module = new TranslationModule();
            PrivateFieldAccess.SetField(module, "_languages", PrivateFieldAccess.BuildList(EntryType, languages));
            return module;
        }

        [Test]
        public void GenerateCode_EmptyLanguages_ReturnsStub()
        {
            string expected =
$@"// <auto-generated/>
// Generated by TsvrcGenerator. Do not edit, changes will be overwritten.
// Regenerated automatically on domain reload, or manually via Tsvrc > Force Regenerate.

using UdonSharp;
using UnityEngine;

namespace {ScaffoldModule.CompiledNamespace}
{{
    public enum Language {{ }}

    public partial class {ScaffoldModule.CompiledClassName}
    {{
        public void SetLanguage(Language lang)
        {{
        }}
        public string Translate(string key)
        {{
            return key;
        }}
        public string Translate(string key, string param)
        {{
            return key;
        }}
        public void SubscribeLanguageChanged(UdonSharpBehaviour listener, string callback)
        {{
        }}
        public void _TsApplyTranslationBatch()
        {{
        }}
    }}
}}
";

            GeneratedCodeAssert.AreEqual(expected, BuildModule().GenerateCode());
        }

        [Test]
        public void GenerateCode_SingleLanguage_DeclaresEnumMemberAndKeyValueArrays()
        {
            var module = BuildModule(Language("en", "English", ("_hello_", "Hello")));

            string code = module.GenerateCode();

            StringAssert.Contains("public enum Language { English }", code);
            StringAssert.Contains("private string[] _tsKeys_en = new string[] { \"_hello_\" };", code);
            StringAssert.Contains("private string[] _tsVals_en = new string[] { \"Hello\" };", code);
        }

        [Test]
        public void GenerateCode_SingleLanguage_SetLanguageHasSingleIfWithElseErrorFallback()
        {
            var module = BuildModule(Language("en", "English", ("_hello_", "Hello")));

            string code = module.GenerateCode();

            StringAssert.Contains("if (_tsIdx == 0) { _tsCurrentKeys = _tsKeys_en; _tsCurrentVals = _tsVals_en; }", code);
            StringAssert.DoesNotContain("else if", code);
            StringAssert.Contains("Debug.LogError", code);
            StringAssert.Contains("is not available.", code);

            // Candidate bug (CODEGEN_TESTING_PLAN.md Part 4 item 6): the generated line's
            // interpolated string escapes `_tsIdx` as a *literal* brace pair, not an
            // interpolation hole - at runtime this logs the literal text "{_tsIdx}", never
            // the actual invalid index value. Pinning the exact text here (verified against
            // real Unity output, not hand-derived) so this either gets fixed deliberately or
            // this test visibly needs updating if the escaping ever changes.
            StringAssert.Contains(
                "else { Debug.LogError($\"[TsvrcGenerated] Language index {{_tsIdx}} is not available.\"); return; }",
                code);
        }

        [Test]
        public void GenerateCode_MultipleLanguages_SetLanguageChainsIfElseIfElse()
        {
            var module = BuildModule(
                Language("en", "English", ("_hi_", "Hi")),
                Language("fr", "French", ("_hi_", "Salut")));

            string code = module.GenerateCode();

            StringAssert.Contains("if (_tsIdx == 0) { _tsCurrentKeys = _tsKeys_en; _tsCurrentVals = _tsVals_en; }", code);
            StringAssert.Contains("else if (_tsIdx == 1) { _tsCurrentKeys = _tsKeys_fr; _tsCurrentVals = _tsVals_fr; }", code);
            StringAssert.Contains("public enum Language { English, French }", code);
        }

        [Test]
        public void GenerateCode_EscapesSpecialCharactersInKeysAndValues()
        {
            var module = BuildModule(Language("en", "English", ("_q_", "Say \"hi\"\nnow\\then")));

            string code = module.GenerateCode();

            StringAssert.Contains("Say \\\"hi\\\"\\nnow\\\\then", code);
        }

        [Test]
        public void GenerateCode_HardcodedBatchSizeOf20AppearsInApplyTranslationBatch()
        {
            var module = BuildModule(Language("en", "English", ("_a_", "A")));

            string code = module.GenerateCode();

            StringAssert.Contains("Mathf.Min(_tsBatchIndex + 20, _translationTargets.Length)", code);
        }
    }
}
